"""TP1-R50-READJUDICATION-2026-08-23 -- EXTENDED RE-ADJUDICATION of the frozen prereg cell
R_tp100_f50 (analysis/recommendations/prereg-tp1-reachability-2026-08-06.json), per J's
extended-re-adjudication brief (2026-08-23). Cell R_tp100_f50 failed EXACTLY ONE gate
(G4_subwindow_stable) in the original 2026-08-06 run for a POWER reason, not an instability
reason: all 4 sub-windows were positive but only 2/4 had >=5 changed trades (G4 requires
>=3 of >=2 qualifying windows). This file extends popA's entry window forward through the
live OPRA cache last date to give G4 more data, WITHOUT touching any gate definition.

PRECEDENT COPIED EXACTLY (per brief): backtest/tools/gate_revalidation_structure_veto_extended_
2026_08_23.py -- reuse every pure function from the ORIGINAL frozen runner verbatim (import,
never re-implement), extend only WHICH DATA feeds them, and read the live OPRA cache last date
via autoresearch.recency_check.read_cache_last_date() -- never hardcoded.

REUSE MAP (verbatim imports, zero re-implementation of gate/scoring logic):
  backtest/tools/tp1_reachability_2026_08_06.py (as `tp1r`):
    shape_for, REGISTRY_SHAPES, ARM_EXIT_PATCH (frozen 2026-08-06 snapshot -- see DRIFT
    DISCLOSURE below), build_ribbon_lookup, ribbon_tick_df_for, walk_population_a,
    one_sample_p, bh_fdr, score_popa_cell, SUBWINDOWS (its 4th window's END DATE is the only
    thing this file changes -- a DATA boundary, not gate logic; the prereg brief explicitly
    authorizes this: "window boundaries stay 2025H1/2025H2/2026Q1/2026-04-01..(new end)").
  backtest/tools/engine_fullhist_replay.py (as `efr`):
    SAFE_BASE_LIVE (the ENTRY-layer engine_cli-equivalent config, unchanged), naive_dt.
    Its own build_ribbon_lookup/ribbon_tick_df_for are byte-identical to tp1r's copies
    (both trace to the same original source); tp1r's copies are used throughout for a single
    call site.
  backtest/lib/orchestrator.run_backtest -- the ENTRY layer (score+gate+filter cascade),
  backtest/lib/exit_manager_walk.walk_exit_manager -- the ONLY exit re-derivation path
    (NEVER simulator_real -- 2026-07-09 SIM-EXIT-SHAPE-PARITY scar),
  backtest/lib/option_pricing_real.{load_contract_bars,option_symbol},
  backtest/tools/elite_bear_level_reject_gate_ab.{entry_date,classify_tier} (eb).

DRIFT DISCLOSURE (found this session, disclosed not silently "fixed"): automation/state/fleet/
strategies.py's LIVE ribbon_ride exit shape has CHANGED since the 2026-08-06 prereg was frozen
-- commits 658ecc79 (2026-08-10) and 20a9e792/e3a44956 (2026-08-11/12) added `pre_tp1_ladder=
[[0.50,0.30],[0.75,0.60]]` and `pre_tp1_trail_arm_pct=0.75` to the ARMED live registry shape.
tp1_reachability_2026_08_06.py's REGISTRY_SHAPES["ribbon_ride"] dict does NOT have these keys
-- it is a byte-identical snapshot of the shape AS OF 2026-08-06, frozen by the prereg's cell
definitions. Per the brief's absolute prohibition on redefining any cell, this file keeps
REGISTRY_SHAPES exactly as tp1r defines it (imported, not copied-and-edited) for BOTH the new
entries' reference/baseline P&L AND the CONTROL/R_tp100_f667/R_tp100_f50 cells -- i.e. this
study answers "does a bigger TP1-fraction-only population clear G4" under the SAME frozen
exit-shape family the prereg registered, not "what does today's live ladder-augmented shape do".
That is a second, separate, undisclosed-until-now finding worth its own future study; it is
NOT folded into this one.

POPULATION A EXTENSION METHOD: the original population (analysis/recommendations/
engine-fullhist-replay-2026-07-23.json, n=191, entries FROZEN, window 2025-01-06..2026-07-21)
is loaded verbatim and NEVER re-walked through the entry layer -- only its exits are re-derived
per-cell (identical to the original tp1_reachability_2026_08_06.py). NEW entries for the window
2026-07-23..<live OPRA cache last date> are generated by an INDEPENDENT re-implementation of
engine_fullhist_replay.py's own entry+reference-exit generation (run_backtest(**SAFE_BASE_LIVE)
for entries; walk_exit_manager with tp1r.REGISTRY_SHAPES["ribbon_ride"] for each new entry's
reference/baseline dollar_pnl) -- kept as a SEPARATE code path from tp1r.walk_population_a
deliberately, so the VOID reconciliation check below is a genuine parity check on the NEW
entries too (not tautological): tp1r.walk_population_a's CONTROL cell re-walk of the SAME new
entries must reconcile to this file's own independently-computed reference P&L with ZERO
mismatches, exactly as the original study's CONTROL cell reconciled against engine_fullhist_
replay.py's separately-generated numbers.

SPY/VIX DATA: backtest/data/spy_5m_2025-01-01_2026-07-22.csv (== the ORIGINAL population's own
SPY_HIST file, so every original entry's underlying bar data is UNCHANGED) concatenated with the
newest rolling daily-append file (spy_5m_2026-05-19_2026-08-21.csv, auto-resolved by filename
pattern, same convention as autoresearch.recency_check._latest_rolling), de-duplicated on
timestamp_et keep='first' (master file's bars win on any overlap -- defensive, though the
run_backtest entry-emission window for new entries starts 2026-07-23, one day past the original
population's own end_date=2026-07-22, so no emitted entry can be affected by the de-dup choice
either way). Same construction for VIX.

ANALYSIS ONLY. No params.json / aggressive/params.json / any trading-path file is touched.
Outputs: analysis/recommendations/tp1-r50-readjudication-2026-08-23.json (+ .md companion,
written by a separate small script that reads this file's JSON).

Run: backtest/.venv/Scripts/python.exe backtest/tools/tp1_r50_readjudication_2026_08_23.py
"""
from __future__ import annotations

import datetime as dt
import json
import sys
import time
from pathlib import Path
from typing import Optional

REPO = Path(__file__).resolve().parents[2]
BACKTEST = REPO / "backtest"
FLEET_DIR = REPO / "automation" / "state" / "fleet"
for _p in (str(BACKTEST), str(BACKTEST / "lib"), str(BACKTEST / "tools"), str(FLEET_DIR), str(REPO),
           str(BACKTEST / "autoresearch")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import pandas as pd  # noqa: E402

import tp1_reachability_2026_08_06 as tp1r  # noqa: E402 -- reuse every gate/metric function verbatim
import engine_fullhist_replay as efr  # noqa: E402 -- reuse SAFE_BASE_LIVE, naive_dt
import elite_bear_level_reject_gate_ab as eb  # noqa: E402 -- entry_date, classify_tier
from lib.orchestrator import run_backtest  # noqa: E402
from lib.exit_manager_walk import walk_exit_manager  # noqa: E402
from lib.option_pricing_real import load_contract_bars, option_symbol  # noqa: E402
from lib.et_frame import parse_timestamp_et as _sanctioned_parse_timestamp_et, FRAME_WALL_V1  # noqa: E402
from recency_check import read_cache_last_date  # noqa: E402

PREREG = REPO / "analysis" / "recommendations" / "prereg-tp1-reachability-2026-08-06.json"
ORIGINAL_SCORECARD = REPO / "analysis" / "recommendations" / "tp1-reachability-2026-08-06.json"
SOURCE_REPLAY = REPO / "analysis" / "recommendations" / "engine-fullhist-replay-2026-07-23.json"
SPY_MASTER = BACKTEST / "data" / "spy_5m_2025-01-01_2026-07-22.csv"   # == original popA's own file
VIX_MASTER = BACKTEST / "data" / "vix_5m_2025-01-01_2026-07-22.csv"
OUT_JSON = REPO / "analysis" / "recommendations" / "tp1-r50-readjudication-2026-08-23.json"

ORIGINAL_POPA_END = dt.date(2026, 7, 22)   # original run_backtest end_date; 07-22 verified ZERO entries
EXT_START = dt.date(2026, 7, 23)           # extension starts strictly after, zero overlap risk
TIME_STOP_A = dt.time(15, 40)              # population A's own convention (matches tp1r + efr)

CELL_IDS = ["CONTROL", "R_tp100_f667", "R_tp100_f50"]
CELLS_BY_ID = {c["id"]: c for c in tp1r.CELLS if c["id"] in CELL_IDS}


def log(m: str) -> None:
    print(f"[tp1-r50-readj] {m}", flush=True)


def _latest_rolling(symbol: str) -> Path:
    """Verbatim convention from autoresearch.recency_check._latest_rolling (newest rolling
    daily-append file by end-date in filename, auto-resolved -- never hardcoded)."""
    import re
    pat = re.compile(rf"^{symbol}_5m_(\d{{4}}-\d{{2}}-\d{{2}})_(\d{{4}}-\d{{2}}-\d{{2}})\.csv$")
    best: Optional[tuple] = None
    for p in (BACKTEST / "data").glob(f"{symbol}_5m_*.csv"):
        m = pat.match(p.name)
        if not m:
            continue
        if best is None or m.group(2) > best[0]:
            best = (m.group(2), p)
    if best is None:
        raise FileNotFoundError(f"no rolling {symbol}_5m_*.csv in backtest/data")
    return best[1]


def _parse_timestamp_et(col: pd.Series) -> pd.Series:
    """Codebase convention (DST-FRAME-BLAST-RADIUS-2026-08-02 / et_frame.py): the OPRA/SPY CSV
    cache's `timestamp_et` column carries a FIXED '-04:00' suffix year-round regardless of
    actual DST state (verified: 2025-01-10 winter rows are still '...-04:00' on disk) -- the
    digits themselves ARE the intended ET wall-clock time; the offset label is a mislabeled
    constant, NOT a real UTC offset. Every existing consumer in this codebase (engine_fullhist_
    replay.py, tp1_reachability_2026_08_06.py, gate_revalidation_ab.py) therefore does a NAIVE
    parse + tz_localize(None) (drop the label, keep the digits) rather than a true UTC round-
    trip. A real utc=True + tz_convert-to-New-York conversion (tried first in this file and
    reverted -- produced 16 mismatches, all on winter dates, in the VOID reconciliation check)
    SHIFTS every winter-month (EST) bar by 1 hour relative to that convention, desynchronizing
    the ribbon/price alignment for winter entries and breaking the VOID reconciliation.

    ROUTED (2026-08-23, DST-FRAME graduated-guard remediation -- test_graduated_guards.py::
    test_dst_frame_no_new_unguarded_opra_join_consumers) through the SANCTIONED
    lib.et_frame.parse_timestamp_et helper with frame=FRAME_WALL_V1 instead of hand-rolling
    the same wall-v1 parse locally. et_frame.py's wall-v1 branch is byte-identical to what
    this function used to do inline (bare pd.to_datetime + conditional tz_localize(None)) --
    this is a code-path compliance fix only, NOT an arithmetic change; the extended
    re-adjudication was re-run after this edit and produced byte-identical output to the
    published verdict (see commit message)."""
    return _sanctioned_parse_timestamp_et(col, frame=FRAME_WALL_V1)


def load_extended_spy_vix() -> tuple[pd.DataFrame, pd.DataFrame]:
    spy_master = pd.read_csv(SPY_MASTER)
    vix_master = pd.read_csv(VIX_MASTER)
    spy_recent = pd.read_csv(_latest_rolling("spy"))
    vix_recent = pd.read_csv(_latest_rolling("vix"))

    # SPY: codebase's established DST-naive convention (see _parse_timestamp_et docstring) --
    # the fixed '-04:00' label is mislabeled, digits ARE the ET wall clock.
    spy_master["timestamp_et"] = _parse_timestamp_et(spy_master["timestamp_et"])
    spy_recent["timestamp_et"] = _parse_timestamp_et(spy_recent["timestamp_et"])
    spy = pd.concat([spy_master, spy_recent], ignore_index=True)
    spy = spy.drop_duplicates(subset="timestamp_et", keep="first").sort_values(
        "timestamp_et").reset_index(drop=True)

    # VIX: unlike SPY, the on-disk offsets are GENUINELY DST-correct (-0500 winter / -0400
    # summer, verified). orchestrator.run_backtest does its OWN pd.to_datetime(utc=True) parse
    # internally (lib/orchestrator.py:234) -- exactly what engine_fullhist_replay.py relies on
    # by passing vix_df through with its timestamp_et column UNTOUCHED. Keep the raw strings;
    # dedupe on a side UTC-parsed key only (master wins on overlap).
    vix = pd.concat([vix_master, vix_recent], ignore_index=True)
    vix["_dedup_utc"] = pd.to_datetime(vix["timestamp_et"], utc=True)
    vix = (vix.drop_duplicates(subset="_dedup_utc", keep="first")
              .sort_values("_dedup_utc").drop(columns=["_dedup_utc"]).reset_index(drop=True))
    return spy, vix


def generate_extension_trades(spy: pd.DataFrame, vix: pd.DataFrame, lookup: pd.DataFrame,
                               cache_last: dt.date) -> tuple[list[dict], dict]:
    """INDEPENDENT re-implementation of engine_fullhist_replay.py's entry+reference-exit
    generation, restricted to [EXT_START, cache_last]. Returns (new_trade_rows, stats)."""
    log(f"ENTRY layer: run_backtest(**SAFE_BASE_LIVE) window {EXT_START}..{cache_last} "
        f"(full spy/vix frame passed for warmup continuity, emission bounded by start/end_date)")
    t0 = time.time()
    r = run_backtest(spy, vix, start_date=EXT_START, end_date=cache_last, **efr.SAFE_BASE_LIVE)
    entry_elapsed = time.time() - t0
    log(f"  {len(r.trades)} raw entries in {entry_elapsed:.1f}s")

    correct_shape = dict(tp1r.REGISTRY_SHAPES["ribbon_ride"])  # FROZEN 2026-08-06 snapshot, see DRIFT DISCLOSURE
    rows: list[dict] = []
    n_no_opra = 0
    n_no_spy_day = 0
    n_out_of_window = 0
    for t in r.trades:
        edate = eb.entry_date(t)
        if edate <= ORIGINAL_POPA_END:
            n_out_of_window += 1
            continue  # defensive: must never overlap the original frozen population
        symbol = option_symbol(edate, int(t.strike), t.side)
        opt_df = load_contract_bars(symbol)
        if opt_df is None:
            n_no_opra += 1
            continue
        day_spy = spy.loc[spy["timestamp_et"].dt.date == edate].reset_index(drop=True)
        if day_spy.empty:
            n_no_spy_day += 1
            continue
        entry_time_et = efr.naive_dt(t.entry_time_et)
        entry_premium = float(t.entry_premium)
        trigger_level = float(t.rejection_level) if t.rejection_level else None
        qty = int(t.qty)
        rtd = tp1r.ribbon_tick_df_for(opt_df, lookup)
        res = walk_exit_manager(
            symbol=symbol, side=t.side, entry_time_et=entry_time_et, entry_premium=entry_premium,
            qty=qty, exit_shape=correct_shape, structure_stop_enabled=True,
            trigger_level=trigger_level, strategy="ribbon_ride", time_stop_et=TIME_STOP_A,
            opt_df=opt_df, ribbon_tick_df=rtd, five_min_spy_df=day_spy,
        )
        rows.append({
            "date": edate.isoformat(), "entry_time_et": entry_time_et.isoformat(),
            "setup": t.setup, "side": t.side, "tier": eb.classify_tier(t.triggers_fired),
            "symbol": symbol, "qty": qty, "entry_premium": round(entry_premium, 4),
            "trigger_level": trigger_level,
            "dollar_pnl": res.dollar_pnl,           # reference/baseline == "src_pnl" for the VOID check
            "exit_reason": res.exit_reason,
            "src_pnl": res.dollar_pnl,               # explicit alias, matches tp1r's ctl_a row shape
        })
    stats = {
        "n_raw_entries": len(r.trades), "n_replayed": len(rows),
        "n_excluded_no_opra_cache": n_no_opra, "n_excluded_no_spy_day": n_no_spy_day,
        "n_excluded_out_of_window_guard": n_out_of_window,
        "entry_layer_seconds": round(entry_elapsed, 1),
    }
    log(f"  EXIT layer (reference shape) done -- n_replayed={len(rows)} "
        f"excluded(no_opra={n_no_opra}, no_spy_day={n_no_spy_day}, guard={n_out_of_window})")
    return rows, stats


def main() -> int:
    t_start = time.time()
    assert PREREG.exists(), "frozen prereg missing"
    assert ORIGINAL_SCORECARD.exists(), "original 2026-08-06 scorecard missing"
    cache_last = read_cache_last_date()
    log(f"live OPRA cache last date: {cache_last}")
    log(f"extension window: {EXT_START}..{cache_last} "
        f"(original popA frozen window ends {ORIGINAL_POPA_END})")

    # ---------- load original frozen population A (unchanged) ----------
    src = json.loads(SOURCE_REPLAY.read_text(encoding="utf-8"))
    original_trades = src["trades"]
    log(f"original popA (frozen): n={len(original_trades)}, "
        f"{original_trades[0]['date']}..{original_trades[-1]['date']}")

    # ---------- extended SPY/VIX frame ----------
    spy, vix = load_extended_spy_vix()
    log(f"  extended spy frame: {len(spy)} rows, {spy['timestamp_et'].min()}..{spy['timestamp_et'].max()}")
    lookup = tp1r.build_ribbon_lookup(spy)

    # ---------- generate NEW entries for the extension window (independent code path) ----------
    new_trades, ext_stats = generate_extension_trades(spy, vix, lookup, cache_last)

    combined_trades = original_trades + new_trades
    log(f"combined population A: n={len(combined_trades)} "
        f"({len(original_trades)} original frozen + {len(new_trades)} new)")

    # ---------- re-walk every cell over the COMBINED population, via tp1r's OWN function ----------
    a_by_cell: dict[str, list[dict]] = {}
    for cid in CELL_IDS:
        cell = CELLS_BY_ID[cid]
        rows = tp1r.walk_population_a(combined_trades, spy, lookup, cell)
        a_by_cell[cid] = rows
        tot = sum(rr["dollar_pnl"] for rr in rows)
        log(f"  {cid:14s} n={len(rows):3d} total=${tot:,.2f}")

    ctl = a_by_cell["CONTROL"]
    # VOID check: CONTROL must reconcile to combined_trades' own src_pnl (dollar_pnl field
    # for original 191, independently-computed reference dollar_pnl for the new entries) with
    # ZERO mismatches > $0.005 -- byte-identical rule to the frozen prereg.
    src_map = {t["symbol"]: t.get("dollar_pnl", t.get("src_pnl")) for t in combined_trades}
    mism = [r for r in ctl if abs(r["dollar_pnl"] - r["src_pnl"]) > 0.005]
    void = len(mism) > 0
    log(f"VOID check: CONTROL reconciliation mismatches = {len(mism)} (MUST be 0)")
    if void:
        log("VOID -- STOPPING before scoring. Mismatches:")
        for m in mism[:20]:
            log(f"    {m['symbol']} {m['date']}: walked={m['dollar_pnl']} src={m['src_pnl']}")

    runner_keys = {(r["symbol"], r["date"]) for r in ctl
                   if r["dollar_pnl"] > 0 and "runner_stop" in str(r["exit_reason"])}
    runner_ctl_total = round(sum(r["dollar_pnl"] for r in ctl
                                  if (r["symbol"], r["date"]) in runner_keys), 2)
    log(f"runner anchor cohort (extended): n={len(runner_keys)} ${runner_ctl_total:,.2f}")

    # ---------- extend G4's 4th sub-window END DATE only (a DATA boundary, per brief) ----------
    original_subwindows = list(tp1r.SUBWINDOWS)
    tp1r.SUBWINDOWS = [
        ("2025H1", "2025-01-01", "2025-06-30"),
        ("2025H2", "2025-07-01", "2025-12-31"),
        ("2026Q1", "2026-01-01", "2026-03-31"),
        ("2026Q2p_ext", "2026-04-01", cache_last.isoformat()),
    ]
    log(f"G4 window boundaries (extended): {tp1r.SUBWINDOWS}")

    results: dict[str, dict] = {}
    for cid in ("R_tp100_f667", "R_tp100_f50"):
        pa = tp1r.score_popa_cell(a_by_cell[cid], ctl, runner_keys)
        gates = {
            "G1_popA_aggregate": pa["aggregate_delta"] > 0.005,
            "G2_ex_best_trade": pa["ex_best_trade"] > 0.005,
            "G3_runner_anchor": pa["runner_cohort_delta"] >= -0.005,
            "G4_subwindow_stable": pa["sub_window_stable"],
            "G5_drop_best_day": pa["drop_best_day"] > 0.005,
        }
        bar = {
            "OOS_positive": pa["oos_2026_delta"] > 0.005,
            "WF_ge_0.70": pa["wf_pass"],
            "sub_window_stable": gates["G4_subwindow_stable"],
            "anchor_no_regression": gates["G3_runner_anchor"],
        }
        results[cid] = {"popA": pa, "gates_popA_scope": gates, "bar_popA_scope": bar}
        log(f"  {cid}: popA delta=${pa['aggregate_delta']:,.2f} runner_delta=${pa['runner_cohort_delta']:,.2f} "
            f"n_changed={pa['n_changed']} sub_windows={pa['sub_windows']} G4={gates['G4_subwindow_stable']}")

    tp1r.SUBWINDOWS = original_subwindows  # restore (defensive; module-level mutation is scoped to this run anyway)

    out = {
        "_doc": __doc__,
        "generated_at_et": dt.datetime.now().isoformat(),
        "runtime_seconds": round(time.time() - t_start, 1),
        "prereg_id": "TP1-REACHABILITY-2026-08-06",
        "readjudication_of": "R_tp100_f50 (ribbon_ride, tp1_premium_pct=1.0, tp1_qty_fraction=0.5); "
                              "control/null cell R_tp100_f667 == live registry AS OF 2026-08-06 (see DRIFT DISCLOSURE)",
        "drift_disclosure": (
            "automation/state/fleet/strategies.py's LIVE ribbon_ride exit shape has CHANGED since "
            "2026-08-06 (commits 658ecc79 2026-08-10, 20a9e792/e3a44956 2026-08-11/12 armed "
            "pre_tp1_ladder=[[0.50,0.30],[0.75,0.60]] + pre_tp1_trail_arm_pct=0.75 on the LIVE "
            "registry). This study's REGISTRY_SHAPES snapshot (imported verbatim from "
            "tp1_reachability_2026_08_06.py, per the frozen-cell prohibition) does NOT include "
            "those keys -- R_tp100_f667 in this scorecard is the null cell AS DEFINED BY THE "
            "FROZEN PREREG, not a re-measurement of what is armed live today. Not folded into "
            "this study; a separate future study would be needed to re-baseline against the "
            "ladder-augmented shape."
        ),
        "cache_last_date": cache_last.isoformat(),
        "original_popA_window": f"{original_trades[0]['date']}..{original_trades[-1]['date']} (n={len(original_trades)}, FROZEN, unchanged)",
        "extension_window": f"{EXT_START.isoformat()}..{cache_last.isoformat()}",
        "extension_stats": ext_stats,
        "combined_popA_n": len(combined_trades),
        "void_check": {
            "void": void,
            "n_mismatches": len(mism),
            "rule": "CONTROL cell (re-walked via tp1r.walk_population_a, an INDEPENDENT code path "
                    "from this file's own reference-P&L generation) must reconcile to each trade's "
                    "own dollar_pnl/src_pnl with ZERO mismatches > $0.005 -- for the original 191 "
                    "this reproduces the 2026-08-06 study's own 0-mismatch result; for the "
                    "extension entries this is a genuine (non-tautological) parity check between "
                    "two independently-coded walk_exit_manager call sites.",
            "mismatches_sample": mism[:20],
        },
        "runner_cohort": {"n": len(runner_keys), "control_total": runner_ctl_total,
                           "note": "recomputed on the COMBINED (191 + extension) population; "
                                   "original study's own figure was n=35 $15,497.25"},
        "g4_subwindow_boundaries_extended": tp1r.SUBWINDOWS,
        "cells": results,
        "combined_control_total": round(sum(r["dollar_pnl"] for r in ctl), 2),
        "gates_frozen_definition_unchanged": tp1r.__doc__ is not None,  # trivially true; the point is no gate text was edited
    }
    if void:
        out["verdict"] = "VOID -- CONTROL reconciliation failed, scorecard not trustworthy. DO NOT ADJUDICATE FURTHER."
    else:
        r50 = results["R_tp100_f50"]
        all_g = r50["gates_popA_scope"]
        clears_popA_gates = all(all_g.values())
        out["verdict"] = ("R_tp100_f50 clears all popA-scope gates on the extended population"
                           if clears_popA_gates else
                           f"R_tp100_f50 still fails: {[k for k,v in all_g.items() if not v]}")
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(out, indent=2, default=str), encoding="utf-8")
    log(f"wrote {OUT_JSON}")
    log(f"VERDICT: {out['verdict']}")
    log(f"done in {time.time() - t_start:.1f}s")
    return 1 if void else 0


if __name__ == "__main__":
    raise SystemExit(main())
