#!/usr/bin/env python3
"""obsidian_vault_sync.py -- render the firm's live state into the Obsidian vault.

WHY (J 2026-08-09): the repo root has been an Obsidian vault since 2026-07-09 and was never
used, because opening it showed a folder of 343 markdown files with no entry point. J's
standing complaint all week has been visibility -- "Gamma works but is invisible" -- while 102
deep-research docs sat unread. This does not build a knowledge system; it builds a READING
SURFACE over state we already produce. Nothing is filed by hand, ever.

Two outputs:
  1. HOME.md          -- the single note you open. Live P&L, positions, armed/shadow, open loops.
  2. journal/<date>.md -- the daily note, with YAML PROPERTIES so Obsidian Bases can table it.

DESIGN CONSTRAINT that shapes everything (verified on Obsidian's docs 2026-08-09): Bases reads
ONLY note frontmatter/properties -- it cannot read external JSON/CSV. We have 659 recommendation
scorecards and 519 state JSONs that are therefore invisible to Obsidian as-is. The fix is not to
migrate them; it is to emit thin notes carrying properties, which is what the frontmatter block
below is for.

IDEMPOTENT + NON-DESTRUCTIVE: the daily note is written by Gamma_Premarket first (Bias, levels,
hypothesis) and by J by hand sometimes. This script therefore (a) injects/updates ONLY the YAML
frontmatter block and (b) replaces ONLY the region between the GAMMA-EOD markers. Everything a
human or another producer wrote is preserved byte-for-byte.

FAILS OPEN: any broker/file error degrades that section to a stated "unavailable" line rather
than raising -- a reporting script must never be able to break a trading day (C7).
Pure stdlib + the repo's own fleet_broker. $0. Places no orders. Reads only.

Usage:
    python setup/scripts/obsidian_vault_sync.py            # HOME + today's daily note
    python setup/scripts/obsidian_vault_sync.py --home-only
    python setup/scripts/obsidian_vault_sync.py --date 2026-08-07
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import urllib.request
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]
FLEET_DIR = REPO / "automation" / "state" / "fleet"
STATE = REPO / "automation" / "state"
JOURNAL = REPO / "journal"

ARMS = ("safe-2", "bold-2", "safe-3", "risky-1", "risky-3")

EOD_BEGIN = "<!-- GAMMA-EOD:BEGIN (generated by obsidian_vault_sync.py -- edits here are overwritten) -->"
EOD_END = "<!-- GAMMA-EOD:END -->"


# --------------------------------------------------------------------------- helpers
def et_now() -> tuple[str, str, bool]:
    """(date, 'YYYY-MM-DD HH:MM:SS Day TZ', market_open). NEVER use bash TZ -- box is Mountain."""
    try:
        out = subprocess.run(
            [sys.executable, str(REPO / "setup" / "scripts" / "et_clock.py")],
            capture_output=True, text=True, timeout=30,
        ).stdout
        lines = [ln.strip() for ln in out.splitlines() if ln.strip()]
        stamp = lines[0]
        market = any("market_hours=True" in ln for ln in lines)
        return stamp.split()[0], stamp, market
    except Exception:  # noqa: BLE001 -- fail open
        return "unknown", "unknown (et_clock unavailable)", False


def read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except Exception:  # noqa: BLE001
        return None


def money(x: float) -> str:
    return f"{x:+,.2f}"


# --------------------------------------------------------------------------- broker
def broker_snapshot() -> dict:
    """Live equity / day delta / open positions per arm. Fails open to an empty snapshot."""
    snap: dict = {"ok": False, "arms": {}, "total_day": 0.0, "error": None}
    try:
        sys.path.insert(0, str(FLEET_DIR))
        import fleet_broker as fb  # type: ignore

        creds = fb.load_creds()
        total = 0.0
        for arm in ARMS:
            try:
                c = creds[arm]
                acct = fb.get_account(c)
                eq = float(acct["equity"])
                sod = float(acct.get("last_equity") or eq)
                positions = [
                    {
                        "symbol": p["symbol"][-9:],
                        "qty": p["qty"],
                        "entry": p["avg_entry_price"],
                        "now": p["current_price"],
                        "upl": float(p["unrealized_pl"]),
                    }
                    for p in fb.open_spy_option_positions(c)
                ]
                snap["arms"][arm] = {
                    "equity": eq, "day": eq - sod, "positions": positions, "error": None,
                }
                total += eq - sod
            except Exception as exc:  # noqa: BLE001 -- per-arm fail open
                snap["arms"][arm] = {
                    "equity": None, "day": 0.0, "positions": [], "error": str(exc)[:80],
                }
        snap["total_day"] = total
        snap["ok"] = True
    except Exception as exc:  # noqa: BLE001
        snap["error"] = str(exc)[:160]
    return snap


def fills_for(date: str) -> dict[str, list[dict]]:
    """Broker fills per arm for `date`, ET-adjusted. Fails open to {}."""
    out: dict[str, list[dict]] = {}
    try:
        sys.path.insert(0, str(FLEET_DIR))
        import fleet_broker as fb  # type: ignore

        creds = fb.load_creds()
        for arm in ARMS:
            try:
                c = creds[arm]
                req = urllib.request.Request(
                    f"{c['base_url']}/v2/orders?status=all&limit=100&direction=desc",
                    headers={"APCA-API-KEY-ID": c["key"], "APCA-API-SECRET-KEY": c["secret"]},
                )
                with urllib.request.urlopen(req, timeout=25) as r:
                    orders = json.load(r)
                rows = []
                for o in orders:
                    fa = str(o.get("filled_at") or "")
                    if not fa.startswith(date) or "SPY" not in str(o.get("symbol", "")):
                        continue
                    hh = int(fa[11:13]) - 4  # UTC -> ET
                    rows.append({
                        "et": f"{hh:02d}:{fa[14:16]}",
                        "side": o["side"],
                        "qty": o["filled_qty"],
                        "px": o["filled_avg_price"],
                        "sym": o["symbol"][-9:],
                        "_sort": fa,
                    })
                out[arm] = sorted(rows, key=lambda r: r["_sort"])
            except Exception:  # noqa: BLE001
                out[arm] = []
    except Exception:  # noqa: BLE001
        pass
    return out


def engine_view(date: str) -> dict:
    """Verdict census + last tick from the core ledger. Fails open."""
    info = {"ticks": 0, "verdicts": {}, "last": None}
    path = STATE / "core-decisions.jsonl"
    try:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            line = line.strip()
            if not line or date not in line:
                continue
            try:
                row = json.loads(line)
            except Exception:  # noqa: BLE001
                continue
            if not str(row.get("ts_et", "")).startswith(date):
                continue
            info["ticks"] += 1
            v = str(row.get("action") or row.get("verdict") or "?")
            info["verdicts"][v] = info["verdicts"].get(v, 0) + 1
            info["last"] = row
    except Exception:  # noqa: BLE001
        pass
    return info


# --------------------------------------------------------------------------- rendering
def render_positions_table(snap: dict) -> list[str]:
    if not snap.get("ok"):
        return [f"> ⚠️ Broker snapshot unavailable: `{snap.get('error')}`", ""]
    out = ["| Arm | Equity | Day | Holding |", "|---|---:|---:|---|"]
    for arm in ARMS:
        a = snap["arms"].get(arm, {})
        if a.get("error"):
            out.append(f"| {arm} | — | — | ⚠️ {a['error']} |")
            continue
        eq = a.get("equity")
        held = " · ".join(
            f"{p['symbol']} ×{p['qty']} @{p['entry']} → {p['now']} ({money(p['upl'])})"
            for p in a.get("positions", [])
        ) or "flat"
        out.append(f"| {arm} | {eq:,.2f} | **{money(a['day'])}** | {held} |")
    out.append(f"| **BOOK** | | **{money(snap['total_day'])}** | |")
    out.append("")
    return out


def build_home(date: str, stamp: str, market_open: bool, snap: dict) -> str:
    levels = read_json(STATE / "key-levels.json") or {}
    bias = read_json(STATE / "today-bias.json") or {}
    eng = engine_view(date)

    L: list[str] = []
    L.append("# 🎛️ Gamma — HOME")
    L.append("")
    L.append(f"> Auto-generated `{stamp}` · market **{'OPEN' if market_open else 'CLOSED'}** · "
             "regenerate: `python setup/scripts/obsidian_vault_sync.py`")
    L.append("> Nothing here is hand-maintained. If a number looks stale, the producer behind it is stale.")
    L.append("")

    L.append("## Position & P&L")
    L.append("")
    L.extend(render_positions_table(snap))

    L.append("## Today's levels")
    L.append("")
    lv = levels.get("levels") or []
    if lv:
        L.append(f"*as of `{levels.get('as_of', '?')}`*")
        L.append("")
        for item in lv:
            L.append(f"- **{item.get('price')}** — {item.get('label') or item.get('name') or ''}")
    else:
        L.append("> ⚠️ No levels loaded — check `automation/state/key-levels.json` freshness.")
    L.append("")

    L.append("## What the engine sees")
    L.append("")
    if eng["ticks"]:
        census = " · ".join(f"`{k}` {v}" for k, v in sorted(
            eng["verdicts"].items(), key=lambda kv: -kv[1])[:6])
        L.append(f"- **{eng['ticks']} ticks** today — {census}")
        last = eng["last"] or {}
        L.append(
            f"- last tick `{last.get('ts_et', '?')}` — spy **{last.get('spy')}** · "
            f"ribbon **{last.get('ribbon')}** · vix {last.get('vix')} · "
            f"bull **{last.get('bull_score')}** / bear **{last.get('bear_score')}**"
        )
        bt = last.get("bull_triggers_raw")
        bb = last.get("bull_blockers")
        if bt or bb:
            L.append(f"- bull triggers `{bt}` · blocked by `{bb}`")
    else:
        L.append(f"> No core decision rows for {date} (weekend, holiday, or the engine is dark).")
    L.append(f"- bias: **{bias.get('bias', 'n/a')}**")
    L.append("")

    L.append("## Open loops")
    L.append("")
    L.append("- [[automation/overnight/STATUS|STATUS]] — known-broken + the REVOKE surface")
    L.append("- [[automation/overnight/queue|queue]] — everything preregged with its forward clock")
    L.append("- [[analysis/deep-research/WEEK-ORDER-2026-08-10|THE WEEK ORDER]] — this week's armed state")
    L.append("- [[CLAUDE|CLAUDE.md]] — doctrine · [[markdown/README|markdown index]]")
    L.append("")
    L.append("## Daily notes")
    L.append("")
    recent = sorted(JOURNAL.glob("20*.md"), reverse=True)[:7]
    for p in recent:
        L.append(f"- [[journal/{p.stem}|{p.stem}]]")
    L.append("")
    return "\n".join(L)


def build_eod_block(date: str, stamp: str, snap: dict, fills: dict, eng: dict) -> str:
    L = [EOD_BEGIN, ""]
    L.append(f"## EOD — auto ({stamp})")
    L.append("")
    L.extend(render_positions_table(snap))

    total_legs = sum(len(v) for v in fills.values())
    L.append(f"### Fills — {total_legs} legs")
    L.append("")
    if total_legs:
        for arm in ARMS:
            rows = fills.get(arm) or []
            if not rows:
                continue
            L.append(f"**{arm}**")
            L.append("")
            for r in rows:
                L.append(f"- `{r['et']}` {r['side']} {r['qty']} @ {r['px']} — {r['sym']}")
            L.append("")
    else:
        L.append("- No SPY option fills.")
        L.append("")

    L.append("### Engine")
    L.append("")
    if eng["ticks"]:
        for k, v in sorted(eng["verdicts"].items(), key=lambda kv: -kv[1])[:8]:
            L.append(f"- `{k}` × {v}")
    else:
        L.append("- No decision rows.")
    L.append("")
    L.append(EOD_END)
    return "\n".join(L)


def upsert_frontmatter(body: str, props: dict) -> str:
    """Insert or update ONLY the keys we own; preserve any other frontmatter verbatim."""
    lines = [f"{k}: {v}" for k, v in props.items()]
    block = "---\n" + "\n".join(lines) + "\n---\n"
    if body.startswith("---\n"):
        end = body.find("\n---\n", 4)
        if end != -1:
            existing = body[4:end].splitlines()
            owned = set(props.keys())
            kept = [ln for ln in existing if ln.split(":")[0].strip() not in owned]
            merged = "---\n" + "\n".join(kept + lines) + "\n---\n"
            return merged + body[end + 5:]
    return block + body


def write_daily(date: str, stamp: str, snap: dict) -> Path:
    fills = fills_for(date)
    eng = engine_view(date)
    path = JOURNAL / f"{date}.md"
    body = path.read_text(encoding="utf-8", errors="replace") if path.exists() else f"# {date}\n\n"

    # Bases-queryable properties -- this is the whole reason the daily note has frontmatter.
    props = {
        "date": date,
        "pnl_book": f"{snap.get('total_day', 0.0):.2f}",
        "legs": sum(len(v) for v in fills.values()),
        "engine_ticks": eng["ticks"],
        "flat_at_write": "true" if all(
            not a.get("positions") for a in snap.get("arms", {}).values()
        ) else "false",
        "generated": stamp,
    }
    for arm in ARMS:
        props[f"pnl_{arm.replace('-', '')}"] = f"{snap.get('arms', {}).get(arm, {}).get('day', 0.0):.2f}"

    body = upsert_frontmatter(body, props)
    block = build_eod_block(date, stamp, snap, fills, eng)
    if EOD_BEGIN in body and EOD_END in body:
        body = re.sub(
            re.escape(EOD_BEGIN) + r".*?" + re.escape(EOD_END), block, body, flags=re.S
        )
    else:
        body = body.rstrip() + "\n\n" + block + "\n"

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Render firm state into the Obsidian vault.")
    ap.add_argument("--date", default=None, help="YYYY-MM-DD (default: today ET)")
    ap.add_argument("--home-only", action="store_true")
    args = ap.parse_args(argv)

    today, stamp, market_open = et_now()
    date = args.date or today
    snap = broker_snapshot()

    home = REPO / "HOME.md"
    home.write_text(build_home(date, stamp, market_open, snap), encoding="utf-8")
    print(f"[obsidian] wrote {home.relative_to(REPO)}")

    if not args.home_only:
        p = write_daily(date, stamp, snap)
        print(f"[obsidian] wrote {p.relative_to(REPO)}")

    print(f"[obsidian] book day P&L {money(snap.get('total_day', 0.0))} · broker_ok={snap.get('ok')}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    try:
        sys.exit(main())
    except Exception as exc:  # noqa: BLE001 -- fail open, never break a caller
        print(f"obsidian_vault_sync: non-fatal error: {exc}")
        sys.exit(0)
