#!/usr/bin/env python3
"""obsidian_vault_sync.py -- render the firm's live state into the Obsidian vault.

WHY (J 2026-08-09): the repo root has been an Obsidian vault since 2026-07-09 and was never
used, because opening it showed a folder of 343 markdown files with no entry point. J's
standing complaint all week has been visibility -- "Gamma works but is invisible" -- while 102
deep-research docs sat unread. This does not build a knowledge system; it builds a READING
SURFACE over state we already produce. Nothing is filed by hand, ever.

Two outputs:
  1. HOME.md          -- the single note you open. Live P&L, positions, armed/shadow, open loops.
  2. journal/<date>.md -- the daily note, with YAML PROPERTIES so Obsidian Bases can table it.

DESIGN CONSTRAINT that shapes everything (verified on Obsidian's docs 2026-08-09): Bases reads
ONLY note frontmatter/properties -- it cannot read external JSON/CSV. We have 659 recommendation
scorecards and 519 state JSONs that are therefore invisible to Obsidian as-is. The fix is not to
migrate them; it is to emit thin notes carrying properties, which is what the frontmatter block
below is for.

IDEMPOTENT + NON-DESTRUCTIVE: the daily note is written by Gamma_Premarket first (Bias, levels,
hypothesis) and by J by hand sometimes. This script therefore (a) injects/updates ONLY the YAML
frontmatter block and (b) replaces ONLY the region between the GAMMA-EOD markers. Everything a
human or another producer wrote is preserved byte-for-byte.

FAILS OPEN: any broker/file error degrades that section to a stated "unavailable" line rather
than raising -- a reporting script must never be able to break a trading day (C7).
Pure stdlib + the repo's own fleet_broker. $0. Places no orders. Reads only.

Usage:
    python setup/scripts/obsidian_vault_sync.py            # HOME + today's daily note
    python setup/scripts/obsidian_vault_sync.py --home-only
    python setup/scripts/obsidian_vault_sync.py --date 2026-08-07
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import urllib.request
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]
# CREATE_NO_WINDOW: et_clock.py runs under console-subsystem python here, which flashes a
# console on J's desktop without the flag (2026-08-09 popup sweep).
_CREATE_NO_WINDOW = 0x08000000 if sys.platform == "win32" else 0

FLEET_DIR = REPO / "automation" / "state" / "fleet"
STATE = REPO / "automation" / "state"
JOURNAL = REPO / "journal"

ARMS = ("safe-2", "bold-2", "safe-3", "risky-1", "risky-3")

EOD_BEGIN = "<!-- GAMMA-EOD:BEGIN (generated by obsidian_vault_sync.py -- edits here are overwritten) -->"
EOD_END = "<!-- GAMMA-EOD:END -->"


# --------------------------------------------------------------------------- helpers
def et_now() -> tuple[str, str, bool]:
    """(date, 'YYYY-MM-DD HH:MM:SS Day TZ', market_open). NEVER use bash TZ -- box is Mountain."""
    try:
        out = subprocess.run(
            [sys.executable, str(REPO / "setup" / "scripts" / "et_clock.py")],
            capture_output=True, text=True, timeout=30,
            creationflags=_CREATE_NO_WINDOW,
        ).stdout
        lines = [ln.strip() for ln in out.splitlines() if ln.strip()]
        stamp = lines[0]
        market = any("market_hours=True" in ln for ln in lines)
        return stamp.split()[0], stamp, market
    except Exception:  # noqa: BLE001 -- fail open
        return "unknown", "unknown (et_clock unavailable)", False


def read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except Exception:  # noqa: BLE001
        return None


def money(x: float) -> str:
    return f"{x:+,.2f}"


# --------------------------------------------------------------------------- broker
def broker_snapshot() -> dict:
    """Live equity / day delta / open positions per arm. Fails open to an empty snapshot."""
    snap: dict = {"ok": False, "arms": {}, "total_day": 0.0, "error": None}
    try:
        sys.path.insert(0, str(FLEET_DIR))
        import fleet_broker as fb  # type: ignore

        creds = fb.load_creds()
        total = 0.0
        for arm in ARMS:
            try:
                c = creds[arm]
                acct = fb.get_account(c)
                eq = float(acct["equity"])
                sod = float(acct.get("last_equity") or eq)
                positions = [
                    {
                        "symbol": p["symbol"][-9:],
                        "qty": p["qty"],
                        "entry": p["avg_entry_price"],
                        "now": p["current_price"],
                        "upl": float(p["unrealized_pl"]),
                    }
                    for p in fb.open_spy_option_positions(c)
                ]
                snap["arms"][arm] = {
                    "equity": eq, "day": eq - sod, "positions": positions, "error": None,
                }
                total += eq - sod
            except Exception as exc:  # noqa: BLE001 -- per-arm fail open
                snap["arms"][arm] = {
                    "equity": None, "day": 0.0, "positions": [], "error": str(exc)[:80],
                }
        snap["total_day"] = total
        snap["ok"] = True
    except Exception as exc:  # noqa: BLE001
        snap["error"] = str(exc)[:160]
    return snap


def fills_for(date: str) -> dict[str, list[dict]]:
    """Broker fills per arm for `date`, ET-adjusted. Fails open to {}."""
    out: dict[str, list[dict]] = {}
    try:
        sys.path.insert(0, str(FLEET_DIR))
        import fleet_broker as fb  # type: ignore

        creds = fb.load_creds()
        for arm in ARMS:
            try:
                c = creds[arm]
                req = urllib.request.Request(
                    f"{c['base_url']}/v2/orders?status=all&limit=100&direction=desc",
                    headers={"APCA-API-KEY-ID": c["key"], "APCA-API-SECRET-KEY": c["secret"]},
                )
                with urllib.request.urlopen(req, timeout=25) as r:
                    orders = json.load(r)
                rows = []
                for o in orders:
                    fa = str(o.get("filled_at") or "")
                    if not fa.startswith(date) or "SPY" not in str(o.get("symbol", "")):
                        continue
                    hh = int(fa[11:13]) - 4  # UTC -> ET
                    rows.append({
                        "et": f"{hh:02d}:{fa[14:16]}",
                        "side": o["side"],
                        "qty": o["filled_qty"],
                        "px": o["filled_avg_price"],
                        "sym": o["symbol"][-9:],
                        "_sort": fa,
                    })
                out[arm] = sorted(rows, key=lambda r: r["_sort"])
            except Exception:  # noqa: BLE001
                out[arm] = []
    except Exception:  # noqa: BLE001
        pass
    return out


def engine_view(date: str) -> dict:
    """Verdict census + last tick from the core ledger. Fails open."""
    info = {"ticks": 0, "verdicts": {}, "last": None}
    path = STATE / "core-decisions.jsonl"
    try:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            line = line.strip()
            if not line or date not in line:
                continue
            try:
                row = json.loads(line)
            except Exception:  # noqa: BLE001
                continue
            if not str(row.get("ts_et", "")).startswith(date):
                continue
            info["ticks"] += 1
            v = str(row.get("action") or row.get("verdict") or "?")
            info["verdicts"][v] = info["verdicts"].get(v, 0) + 1
            info["last"] = row
    except Exception:  # noqa: BLE001
        pass
    return info


# --------------------------------------------------------------------------- rendering
def render_positions_table(snap: dict) -> list[str]:
    if not snap.get("ok"):
        return [f"> ⚠️ Broker snapshot unavailable: `{snap.get('error')}`", ""]
    out = ["| Arm | Equity | Day | Holding |", "|---|---:|---:|---|"]
    for arm in ARMS:
        a = snap["arms"].get(arm, {})
        if a.get("error"):
            out.append(f"| {arm} | — | — | ⚠️ {a['error']} |")
            continue
        eq = a.get("equity")
        eq_s = f"{eq:,.2f}" if isinstance(eq, (int, float)) else "—"
        held = " · ".join(
            f"{p['symbol']} ×{p['qty']} @{p['entry']} → {p['now']} ({money(p['upl'])})"
            for p in a.get("positions", [])
        ) or "flat"
        out.append(f"| {arm} | {eq_s} | **{money(a['day'])}** | {held} |")
    out.append(f"| **BOOK** | | **{money(snap['total_day'])}** | |")
    out.append("")
    return out


def build_home(date: str, stamp: str, market_open: bool, snap: dict) -> str:
    levels = read_json(STATE / "key-levels.json") or {}
    bias = read_json(STATE / "today-bias.json") or {}
    eng = engine_view(date)

    L: list[str] = []
    L.append("# 🎛️ Gamma — HOME")
    L.append("")
    L.append(f"> Auto-generated `{stamp}` · market **{'OPEN' if market_open else 'CLOSED'}** · "
             "regenerate: `python setup/scripts/obsidian_vault_sync.py`")
    L.append("> Nothing here is hand-maintained. If a number looks stale, the producer behind it is stale.")
    L.append("")

    L.append("## Position & P&L")
    L.append("")
    L.extend(render_positions_table(snap))

    L.append("## Today's levels")
    L.append("")
    lv = levels.get("levels") or []
    if lv:
        L.append(f"*as of `{levels.get('as_of', '?')}`*")
        L.append("")
        for item in lv:
            L.append(f"- **{item.get('price')}** — {item.get('label') or item.get('name') or ''}")
    else:
        L.append("> ⚠️ No levels loaded — check `automation/state/key-levels.json` freshness.")
    L.append("")

    L.append("## What the engine sees")
    L.append("")
    if eng["ticks"]:
        census = " · ".join(f"`{k}` {v}" for k, v in sorted(
            eng["verdicts"].items(), key=lambda kv: -kv[1])[:6])
        L.append(f"- **{eng['ticks']} ticks** today — {census}")
        last = eng["last"] or {}
        L.append(
            f"- last tick `{last.get('ts_et', '?')}` — spy **{last.get('spy')}** · "
            f"ribbon **{last.get('ribbon')}** · vix {last.get('vix')} · "
            f"bull **{last.get('bull_score')}** / bear **{last.get('bear_score')}**"
        )
        bt = last.get("bull_triggers_raw")
        bb = last.get("bull_blockers")
        if bt or bb:
            L.append(f"- bull triggers `{bt}` · blocked by `{bb}`")
    else:
        L.append(f"> No core decision rows for {date} (weekend, holiday, or the engine is dark).")
    L.append(f"- bias: **{bias.get('bias', 'n/a')}**")
    L.append("")

    L.append("## Open loops")
    L.append("")
    L.append("- [[automation/overnight/STATUS|STATUS]] — known-broken + the REVOKE surface")
    L.append("- [[automation/overnight/queue|queue]] — everything preregged with its forward clock")
    L.append("- [[analysis/deep-research/WEEK-ORDER-2026-08-10|THE WEEK ORDER]] — this week's armed state")
    L.append("- [[CLAUDE|CLAUDE.md]] — doctrine · [[markdown/README|markdown index]]")
    L.append("")
    L.append("## Daily notes")
    L.append("")
    recent = sorted(JOURNAL.glob("20*.md"), reverse=True)[:7]
    for p in recent:
        L.append(f"- [[journal/{p.stem}|{p.stem}]]")
    L.append("")
    return "\n".join(L)


def build_eod_block(date: str, stamp: str, snap: dict, fills: dict, eng: dict) -> str:
    L = [EOD_BEGIN, ""]
    L.append(f"## EOD — auto ({stamp})")
    L.append("")
    L.extend(render_positions_table(snap))

    total_legs = sum(len(v) for v in fills.values())
    L.append(f"### Fills — {total_legs} legs")
    L.append("")
    if total_legs:
        for arm in ARMS:
            rows = fills.get(arm) or []
            if not rows:
                continue
            L.append(f"**{arm}**")
            L.append("")
            for r in rows:
                L.append(f"- `{r['et']}` {r['side']} {r['qty']} @ {r['px']} — {r['sym']}")
            L.append("")
    else:
        L.append("- No SPY option fills.")
        L.append("")

    L.append("### Engine")
    L.append("")
    if eng["ticks"]:
        for k, v in sorted(eng["verdicts"].items(), key=lambda kv: -kv[1])[:8]:
            L.append(f"- `{k}` × {v}")
    else:
        L.append("- No decision rows.")
    L.append("")
    L.append(EOD_END)
    return "\n".join(L)


def upsert_frontmatter(body: str, props: dict) -> str:
    """Insert or update ONLY the keys we own; preserve any other frontmatter verbatim."""
    lines = [f"{k}: {v}" for k, v in props.items()]
    block = "---\n" + "\n".join(lines) + "\n---\n"
    if body.startswith("---\n"):
        end = body.find("\n---\n", 4)
        if end != -1:
            existing = body[4:end].splitlines()
            owned = set(props.keys())
            kept = [ln for ln in existing if ln.split(":")[0].strip() not in owned]
            merged = "---\n" + "\n".join(kept + lines) + "\n---\n"
            return merged + body[end + 5:]
    return block + body


def write_daily(date: str, stamp: str, snap: dict) -> Path:
    fills = fills_for(date)
    eng = engine_view(date)
    path = JOURNAL / f"{date}.md"
    body = path.read_text(encoding="utf-8", errors="replace") if path.exists() else f"# {date}\n\n"

    # Bases-queryable properties -- this is the whole reason the daily note has frontmatter.
    props = {
        "date": date,
        "pnl_book": f"{snap.get('total_day', 0.0):.2f}",
        "legs": sum(len(v) for v in fills.values()),
        "engine_ticks": eng["ticks"],
        "flat_at_write": "true" if all(
            not a.get("positions") for a in snap.get("arms", {}).values()
        ) else "false",
        "generated": stamp,
    }
    for arm in ARMS:
        props[f"pnl_{arm.replace('-', '')}"] = f"{snap.get('arms', {}).get(arm, {}).get('day', 0.0):.2f}"

    body = upsert_frontmatter(body, props)
    block = build_eod_block(date, stamp, snap, fills, eng)
    if EOD_BEGIN in body and EOD_END in body:
        body = re.sub(
            re.escape(EOD_BEGIN) + r".*?" + re.escape(EOD_END), block, body, flags=re.S
        )
    else:
        body = body.rstrip() + "\n\n" + block + "\n"

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return path


def read_frontmatter(path: Path) -> dict:
    """Tiny flat YAML frontmatter reader (key: value lines only). Fails open to {}."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
        if not text.startswith("---\n"):
            return {}
        end = text.find("\n---\n", 4)
        if end == -1:
            return {}
        out: dict = {}
        for line in text[4:end].splitlines():
            if ":" in line and not line.startswith(" "):
                k, _, v = line.partition(":")
                out[k.strip()] = v.strip()
        return out
    except Exception:  # noqa: BLE001
        return {}


def build_week_table(n: int = 10) -> list[str]:
    """P&L table over the journal dailies' own frontmatter -- the same data Bases sees."""
    rows = []
    for p in sorted(JOURNAL.glob("20*.md"), reverse=True)[:n]:
        fm = read_frontmatter(p)
        if "pnl_book" not in fm:
            continue
        rows.append((p.stem, fm))
    if not rows:
        return ["> No daily notes carry P&L properties yet.", ""]
    out = ["| Day | Book | safe-2 | bold-2 | safe-3 | risky-1 | risky-3 | Legs |",
           "|---|---:|---:|---:|---:|---:|---:|---:|"]
    for stem, fm in rows:
        out.append(
            f"| [[journal/{stem}\\|{stem}]] | **{fm.get('pnl_book', '?')}** | "
            f"{fm.get('pnl_safe2', '')} | {fm.get('pnl_bold2', '')} | {fm.get('pnl_safe3', '')} | "
            f"{fm.get('pnl_risky1', '')} | {fm.get('pnl_risky3', '')} | {fm.get('legs', '')} |"
        )
    out.append("")
    return out


def build_preregs_board(stamp: str) -> str:
    """SHADOW.md -- every live shadow instrument's tally + the frozen preregs, one glance.

    Only machine-readable sources are auto-summarised; the frozen-prereg section is a stable
    link list (the clocks live in the linked docs -- duplicating them here would rot).
    """
    L = ["# 🕰️ Shadow & Prereg Board", "",
         f"> Auto-generated `{stamp}` by obsidian_vault_sync.py. "
         "Shadow tallies update nightly; a missing tally means that instrument has not fired yet.", ""]

    L.append("## Live shadow instruments")
    L.append("")
    ladder = REPO / "analysis" / "arm-ladder" / "ladder-rung-shadow-ledger.jsonl"
    if ladder.exists():
        lines = [ln for ln in ladder.read_text(encoding="utf-8", errors="replace").splitlines() if ln.strip()]
        last = {}
        try:
            last = json.loads(lines[-1]) if lines else {}
        except Exception:  # noqa: BLE001
            last = {}
        L.append(f"- **Score ladder** (`Gamma_LadderRungShadow`, 16:40 ET) — {len(lines)} session rows; "
                 f"latest: `{json.dumps(last)[:180]}`")
    else:
        L.append("- **Score ladder** (`Gamma_LadderRungShadow`, 16:40 ET) — no rows yet; first fire is the "
                 "next weekday close.")
    hits = sorted(REPO.glob("analysis/entry-quality/*tally*"))
    L.append(f"- **V-d1 / V-e3 entry shadow** (16:25 fold) — "
             + (f"artifact: `{hits[-1].relative_to(REPO)}`" if hits else "no tally artifact found yet."))
    chop = sorted(REPO.glob("analysis/**/chop-meter*"), key=lambda p: p.stat().st_mtime) if REPO.exists() else []
    L.append(f"- **Chop exposure meter** (`Gamma_ChopMeter`, 16:08 ET) — "
             + (f"latest: `{chop[-1].relative_to(REPO)}`" if chop else "artifact appears after the next close."))
    L.append("")

    L.append("## Frozen preregs (clocks live in the linked docs)")
    L.append("")
    for label, rel in (
        ("TP1 sell-half at +100% (R_tp100_f50)", "analysis/deep-research/TP1-REACHABILITY-2026-08-06.md"),
        ("Runner finite 2.5x target", "analysis/deep-research/HOLD-WINNERS-2026-08-06.md"),
        ("B-RR-070 range compression", "analysis/deep-research/CHOP-DEFENSE-2026-08-06.md"),
        ("BRK600 / CAP-3 / CONSEC4 loss guards", "analysis/deep-research/KEEP-LOSSES-SMALL-2026-08-06.md"),
        ("F10 recalibration on live feed", "analysis/deep-research/FRIDAY-2026-08-07-FULL.md"),
        ("Score ladder (held at gate)", "analysis/deep-research/CLOSE-EXECUTION-2026-08-07.md"),
    ):
        note = rel[:-3]
        L.append(f"- **{label}** → [[{note}]]")
    L.append("")
    L.append("## Doctrine anchors")
    L.append("")
    L.append("- [[analysis/deep-research/WEEK-ORDER-2026-08-10|THE WEEK ORDER]] · "
             "[[automation/overnight/STATUS|STATUS]] · [[markdown/doctrine/LESSONS-LEARNED|Lessons]]")
    L.append("")
    return "\n".join(L)


def _live_tasks() -> dict[str, dict]:
    """Live Windows Task Scheduler state for Gamma_* tasks. Fails open to {}."""
    try:
        ps = (
            "Get-ScheduledTask | Where-Object {$_.TaskName -like 'Gamma_*'} | "
            "ForEach-Object { $i=$_|Get-ScheduledTaskInfo; "
            "\"$($_.TaskName)|$($_.State)|$($i.LastTaskResult)\" }"
        )
        out = subprocess.run(["powershell", "-NoProfile", "-Command", ps],
                             capture_output=True, text=True, timeout=90,
                             creationflags=_CREATE_NO_WINDOW).stdout
        res = {}
        for line in out.splitlines():
            parts = line.strip().split("|")
            if len(parts) == 3:
                res[parts[0]] = {"state": parts[1], "last_result": parts[2]}
        return res
    except Exception:  # noqa: BLE001
        return {}


# The architecture, declared once. Each node: (label, path-or-None, one-line role).
# path=None means "runtime concept, no single file". A path that does not exist renders
# with a MISSING marker -- so this map cannot silently describe a system we no longer have.
MAP_SPEC: list[tuple[str, list[tuple[str, str | None, str]]]] = [
    ("🔭 SEE — what the engine perceives", [
        ("Level refresher", "setup/scripts/refresh_levels_intraday.py",
         "writes key-levels.json every 5m; IEX tail keeps it ahead of the window"),
        ("Key levels (state)", "automation/state/key-levels.json",
         "the level set every entry decision is tied to"),
        ("Sight beacon", "setup/scripts/sight_beacon.py",
         "never-blind price feed; REST + fallback"),
        ("Market structure", "crypto/lib/market_structure.py",
         "HH/HL/BOS/CHoCH — the structure-shift detector. NOTE the path: it lives under "
         "crypto/lib but is instrument-agnostic and used by the SPY engine"),
        ("Structure watcher", "backtest/lib/watchers/market_structure_watcher.py",
         "the watcher wrapper the engine actually calls"),
        ("Trendlines", "automation/state/trendlines.json",
         "SHADOW only; producer was dead 47 days, revived 08-06, zero consumers by design"),
    ]),
    ("🧠 DECIDE — scoring and gates", [
        ("Shared signal builder", "automation/state/fleet/build_shared_signal.py",
         "one signal, all arms consume it — this is why arms correlate"),
        ("Filters + scoring", "backtest/lib/filters.py",
         "bull/bear score 0-11; ANY blocker vetoes (entry is binary, not laddered)"),
        ("Strategies", "automation/state/fleet/strategies.py",
         "the 4 live setups + their exit shapes"),
        ("Risk gate", "backtest/lib/risk_gate.py",
         "Rules 5/6/7 — kill switch, per-trade cap, cash settlement"),
        ("Settlement ledger", "setup/scripts/settlement_ledger.py",
         "cash-account T+1 model; feeds the gate for BOTH core accounts"),
    ]),
    ("⚡ ACT — placement and exits", [
        ("Heartbeat core", "setup/scripts/heartbeat_core.py",
         "THE live engine, 1/min RTH — core arms (safe-2, bold-2)"),
        ("Fleet executor", "automation/state/fleet/fleet_executor.py",
         "fleet arms (safe-3, risky-1, risky-3); sizing + admission"),
        ("Exit manager", "automation/state/fleet/exit_manager.py",
         "TP1 / runner / trail / structure stop / -50% catastrophe cap"),
        ("Fleet broker", "automation/state/fleet/fleet_broker.py",
         "the ONLY broker surface; load_creds() takes no args"),
    ]),
    ("📚 LEARN — research and instruments", [
        ("Winner autopsy", "setup/scripts/winner_autopsy.py",
         "capture rate over the winner population, nightly"),
        ("Chop meter", None, "Gamma_ChopMeter 16:08 — ordinal>=4, consec runs, would-trip flags"),
        ("Entry-quality ledger", "setup/scripts/entry_quality_ledger.py",
         "the pay-vs-bleed entry signature; V-d1/V-e3 shadow counters"),
        ("Ladder shadow", None,
         "Gamma_LadderRungShadow 16:40 — logs what the score ladder WOULD admit"),
        ("Trade autopsy", "setup/scripts/trade_autopsy.py",
         "emits hypotheses nightly; its hold_to_time counterfactual is a known artifact"),
    ]),
    ("🗺️ ORIENT — read these, in this order", [
        ("CLAUDE.md", "CLAUDE.md", "the soul file. doctrine, the 10 rules, operating principles"),
        ("THE WEEK ORDER", "analysis/deep-research/WEEK-ORDER-2026-08-10.md",
         "what is armed right now + Monday state"),
        ("STATUS", "automation/overnight/STATUS.md", "REVOKE surface + known-broken"),
        ("SHADOW", "SHADOW.md", "every shadow clock + frozen prereg"),
        ("Lessons", "markdown/doctrine/LESSONS-LEARNED.md", "294 anti-patterns, indexed by theme"),
        ("Architecture", "markdown/specs/ARCHITECTURE.md", "cold-start wiring snapshot"),
        ("markdown index", "markdown/README.md", "the doc taxonomy"),
    ]),
]

CLAUDE_ROUTING = [
    ("Why did/didn't we trade?", "journal/<date> → automation/overnight/STATUS.md"),
    ("What is armed / what changes?", "analysis/deep-research/WEEK-ORDER-2026-08-10.md + SHADOW.md"),
    ("Is X already tested / dead?", "the GRAVEYARD section of the latest EOD, then markdown/doctrine/LESSONS-LEARNED.md"),
    ("How does a decision get made?", "MAP.md §SEE → §DECIDE → §ACT (this file), then filters.py"),
    ("What broke before?", "markdown/doctrine/LESSONS-LEARNED.md (L-numbered, themed C1-C36)"),
    ("What are the rules?", "CLAUDE.md — the 10 rules + OP-0/3/11/16/22/25/31/32/33"),
]


def build_map(stamp: str) -> str:
    tasks = _live_tasks()
    L = ["# 🗺️ Gamma — SYSTEM MAP", "",
         f"> Auto-generated `{stamp}`. Every path is existence-checked at build time, so this "
         "map cannot silently describe a system we no longer have. "
         "`⛔MISSING` = the spec claims a file that is gone.", ""]

    L.append("## For a fresh Claude session — read only the branch you need")
    L.append("")
    L.append("| If the question is… | Read |")
    L.append("|---|---|")
    for q, where in CLAUDE_ROUTING:
        L.append(f"| {q} | {where} |")
    L.append("")
    L.append("**Do not read the whole repo.** 6,777 markdown files exist; ~479 are human-written "
             "and the rest is machine output. This map plus the four ORIENT docs is the "
             "whole system at the level most questions need.")
    L.append("")

    L.append("## The flow, one picture")
    L.append("")
    L.append(MERMAID_FLOW)
    L.append("")

    for section, nodes in MAP_SPEC:
        L.append(f"## {section}")
        L.append("")
        for label, path, role in nodes:
            if path is None:
                L.append(f"- **{label}** — {role}")
                continue
            exists = (REPO / path).exists()
            note = path[:-3] if path.endswith(".md") else None
            link = f"[[{note}\\|{label}]]" if (note and exists) else f"`{path}`"
            mark = "" if exists else "  ⛔MISSING"
            L.append(f"- **{label}** → {link} — {role}{mark}")
        L.append("")

    L.append("## ⏰ The daily loop (live task state)")
    L.append("")
    L.append("| ET | Task | Role | State |")
    L.append("|---|---|---|---|")
    for et, name, role in (
        ("08:00", "Gamma_LaunchTV", "TV + CDP up (no TV = no trades)"),
        ("08:05/5m", "Gamma_TvWatchdog", "keeps CDP alive; heals in ~67s"),
        ("08:30", "Gamma_Premarket", "levels, bias, hypothesis → journal note"),
        ("09:30–15:55", "Gamma_HeartbeatCore", "THE engine, 1/min"),
        ("/5m RTH", "Gamma_LevelRefresh", "key-levels.json freshness"),
        ("15:55", "Gamma_EodFlatten", "nothing 0DTE survives the close"),
        ("16:08", "Gamma_ChopMeter", "did we trade chop today"),
        ("16:25", "Gamma_WinnerAutopsy", "capture rate + entry-quality fold"),
        ("16:40", "Gamma_LadderRungShadow", "score-ladder shadow clock"),
        ("16:45", "Gamma_ObsidianSync", "HOME + daily note + this map"),
        ("17:45", "Gamma_RegimeAttribution", "was that us or the tape"),
    ):
        t = tasks.get(name)
        state = f"{t['state']} (last={t['last_result']})" if t else "⛔ NOT REGISTERED"
        L.append(f"| {et} | `{name}` | {role} | {state} |")
    L.append("")

    L.append("## 💰 The arms — risk profiles, NOT strategies")
    L.append("")
    L.append("All arms trade the SAME shared signal. They differ only in sizing, gates and exit "
             "shape. That is also why they lose together: on 08-07 all four bought the same "
             "contract within 15 seconds.")
    L.append("")
    L.append("| Arm | Class | Distinguishing config |")
    L.append("|---|---|---|")
    for arm, cls, cfg in (
        ("safe-2", "core safe", "cash_settlement · ATM · strict"),
        ("bold-2", "core bold", "cash_settlement (parity fix 08-09) · was PDT-dark 4 sessions"),
        ("safe-3", "fleet safe", "bold tier table · min_triggers=2"),
        ("risky-1", "fleet full-send", "ATM · TP1 +50% exit_patch · L246 floor-rescue"),
        ("risky-3", "fleet loose", "OTM-2 (kill-criterion revert 08-06) · qty10 <$0.50 boost"),
        ("crypto twin", "arm #6", "24/7 mechanism validation; P&L NEVER SPY evidence"),
    ):
        L.append(f"| **{arm}** | {cls} | {cfg} |")
    L.append("")
    L.append("---")
    L.append("")
    L.append("[[HOME]] · [[SHADOW]] · [[CLAUDE|CLAUDE.md]] · [[markdown/README|doc index]]")
    L.append("")
    return "\n".join(L)


MERMAID_FLOW = """```mermaid
flowchart LR
  subgraph SEE
    TV[TradingView CDP] --> SB[sight_beacon]
    ALP[Alpaca REST] --> SB
    LR2[level refresher] --> KL[(key-levels.json)]
  end
  subgraph DECIDE
    SB --> SIG[build_shared_signal]
    KL --> SIG
    SIG --> F[filters.py score 0-11]
    F --> RG[risk_gate R5/R6/R7]
  end
  subgraph ACT
    RG --> HB[heartbeat_core - safe-2 bold-2]
    RG --> FX[fleet_executor - safe-3 risky-1 risky-3]
    HB --> EM[exit_manager]
    FX --> EM
    EM --> BRK[fleet_broker orders]
  end
  BRK --> LED[(decisions.jsonl + fills)]
  LED --> LEARN[nightly: autopsy / chop meter / shadows]
  LEARN -.prereg only.-> F
```"""


# --------------------------------------------------------------------- vault link health
# Target may end with a backslash when the alias pipe is table-escaped ([[x\|alias]]) --
# that backslash belongs to the escape, not the target, so it is stripped after capture.
WIKILINK_RE = re.compile(r"\[\[([^\]|#]+?)\\?(?:#[^\]|]*)?(?:\\?\|[^\]]*)?\]\]")
# Standard markdown links count as inbound too (markdown/README.md uses [text](path.md)) --
# an orphan census that only sees wikilinks would overcount by every README-indexed doc.
MDLINK_RE = re.compile(r"\]\(([^)#\s]+\.md)(?:#[^)]*)?\)")


def _visible_md(cfg_path: Path | None = None) -> list[Path]:
    """The vault's VISIBLE markdown set (mirrors .obsidian/app.json userIgnoreFilters)."""
    try:
        cfg = json.loads((cfg_path or REPO / ".obsidian" / "app.json").read_text(encoding="utf-8"))
        ignores = [f.rstrip("/") for f in cfg.get("userIgnoreFilters", [])]
    except Exception:  # noqa: BLE001
        ignores = []
    out = []
    for p in REPO.rglob("*.md"):
        s = str(p.relative_to(REPO)).replace("\\", "/")
        if s.startswith(".git/"):
            continue
        # ROOT-ANCHORED, matching Obsidian's own userIgnoreFilters semantics. A
        # match-anywhere rule here once hid markdown/doctrine/ (Lessons-Learned!)
        # because the legacy root folder "doctrine/" was excluded.
        if any(s.startswith(f + "/") for f in ignores):
            continue
        out.append(p)
    return out


def mirror_memory() -> int:
    """Copy Claude's persistent memory notes into the vault as memory-mirror/.

    WHY: repo docs wikilink memory notes by name ([[project_fleet_champion_challenger]] etc.)
    but the originals live in ~/.claude/projects/, outside the vault -- unresolvable forever.
    The mirror puts the memory web into the graph and resolves those links.

    ⛔ PUBLIC-REPO CONSTRAINT: memory content (J's preferences, plan details) must NEVER be
    pushed. memory-mirror/ is gitignored -- guarded by test_memory_mirror_is_gitignored.
    Mirror is one-way (memory -> vault); edits here are overwritten, stated in each file? No:
    stated once in _README.md inside the mirror, files copied verbatim.
    """
    src = Path.home() / ".claude" / "projects" / "C--Users-jackw-Desktop-42" / "memory"
    dst = REPO / "memory-mirror"
    if not src.exists():
        return 0
    dst.mkdir(exist_ok=True)
    (dst / "_README.md").write_text(
        "# memory-mirror\n\nGenerated one-way copy of Claude's persistent memory "
        "(~/.claude/projects/.../memory). Edits here are overwritten by "
        "obsidian_vault_sync.py. GITIGNORED -- never pushed (public repo).\n",
        encoding="utf-8")
    n = 0
    for f in src.glob("*.md"):
        try:
            text = f.read_text(encoding="utf-8", errors="replace")
            # Memory notes wikilink each other by their frontmatter `name:` slug (often
            # kebab-case) while filenames are snake_case. Obsidian resolves [[slug]] only
            # if the note carries it as an alias -- inject it into the mirrored copy.
            m = re.search(r"^name:\s*([^\r\n]+)", text, re.M)
            if m and text.startswith("---"):
                slug = m.group(1).strip().strip('"')
                if slug and slug != f.stem and "aliases:" not in text.split("---", 2)[1]:
                    text = text.replace("---\n", f'---\naliases: ["{slug}"]\n', 1)
            (dst / f.name).write_text(text, encoding="utf-8")
            n += 1
        except Exception:  # noqa: BLE001
            continue
    return n


def build_link_health(visible: list[Path]) -> dict:
    """Broken wikilinks + orphan census over the visible set. Pure read, fail-open."""
    by_stem: dict[str, list[str]] = {}
    rels = []
    for p in visible:
        rel = str(p.relative_to(REPO)).replace("\\", "/")
        rels.append(rel)
        by_stem.setdefault(p.stem.lower(), []).append(rel)
        # Aliases + the memory `name:` slug resolve exactly as Obsidian resolves them.
        try:
            head = p.read_text(encoding="utf-8", errors="replace")[:600]
            if head.startswith("---"):
                for fm in re.finditer(r'^(?:name|aliases):\s*\[?\s*"?([^"\r\n\]]+)"?\]?',
                                      head, re.M):
                    slug = fm.group(1).strip()
                    if slug:
                        by_stem.setdefault(slug.lower(), []).append(rel)
        except Exception:  # noqa: BLE001
            pass
    relset = set(rels)

    broken: list[tuple[str, str]] = []
    linked: set[str] = set()
    has_outlink: set[str] = set()
    for p in visible:
        rel = str(p.relative_to(REPO)).replace("\\", "/")
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except Exception:  # noqa: BLE001
            continue
        for m in WIKILINK_RE.finditer(text):
            target = m.group(1).strip().rstrip("\\").replace("\\", "/").rstrip("/")
            if not target:
                continue
            has_outlink.add(rel)
            cand = target if target.endswith(".md") else target + ".md"
            if cand in relset:
                linked.add(cand)
            elif target.split("/")[-1].lower() in by_stem:
                linked.add(by_stem[target.split("/")[-1].lower()][0])
            else:
                broken.append((rel, target))
        # Standard markdown links: resolve relative to the note's own folder, then vault root.
        base = Path(rel).parent
        for m in MDLINK_RE.finditer(text):
            raw = m.group(1).replace("\\", "/")
            has_outlink.add(rel)
            for cand_path in ((base / raw), Path(raw)):
                try:
                    cand = str(cand_path.resolve().relative_to(REPO.resolve())).replace("\\", "/")
                except ValueError:
                    continue
                if cand in relset:
                    linked.add(cand)
                    break

    orphans = [r for r in rels if r not in linked and r not in has_outlink]
    return {"files": len(rels), "broken": broken, "orphans": orphans}


def build_deep_research_index(stamp: str) -> str:
    """Hub note for analysis/deep-research -- one wikilink per doc, grouped by month.

    This single generated hub connects the ~100 research docs to the graph without anyone
    hand-linking anything. Fully regenerated each run (no human content lives here).
    """
    docs = sorted((REPO / "analysis" / "deep-research").glob("*.md"), reverse=True)
    by_month: dict[str, list[str]] = {}
    undated: list[str] = []
    for p in docs:
        if p.name == "INDEX.md":
            continue
        m = re.search(r"(20\d\d)-(\d\d)", p.name)
        key = f"{m.group(1)}-{m.group(2)}" if m else ""
        (by_month.setdefault(key, []) if key else undated).append(p.stem)
    L = ["# 🔬 Deep Research — INDEX", "",
         f"> Auto-generated `{stamp}` by obsidian_vault_sync.py. The graph hub for every "
         "deep-research doc. Do not edit -- regenerated nightly.", ""]
    for month in sorted(by_month, reverse=True):
        L.append(f"## {month}")
        L.append("")
        for stem in by_month[month]:
            L.append(f"- [[analysis/deep-research/{stem}|{stem}]]")
        L.append("")
    if undated:
        L.append("## undated")
        L.append("")
        for stem in undated:
            L.append(f"- [[analysis/deep-research/{stem}|{stem}]]")
        L.append("")
    return "\n".join(L)


JOURNAL_BASE = """\
filters:
  and:
    - file.inFolder("journal")
    - note.pnl_book
views:
  - type: table
    name: "Daily P&L"
    order:
      - file.name
      - note.pnl_book
      - note.legs
      - note.engine_ticks
      - note.pnl_safe2
      - note.pnl_bold2
      - note.pnl_safe3
      - note.pnl_risky1
      - note.pnl_risky3
"""


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Render firm state into the Obsidian vault.")
    ap.add_argument("--date", default=None, help="YYYY-MM-DD (default: today ET)")
    ap.add_argument("--home-only", action="store_true")
    ap.add_argument("--backfill", nargs="*", default=None,
                    help="extra YYYY-MM-DD dates whose daily notes get frontmatter+EOD injected")
    args = ap.parse_args(argv)

    today, stamp, market_open = et_now()
    date = args.date or today
    snap = broker_snapshot()

    if not args.home_only:
        p = write_daily(date, stamp, snap)
        print(f"[obsidian] wrote {p.relative_to(REPO)}")
        for extra in (args.backfill or []):
            # Historical days: /v2/account only knows TODAY's delta, so recompute the day's
            # realized P&L per arm by FIFO over that day's actual broker fills (x100 option
            # multiplier). Real data or nothing -- never zeros presented as P&L (OP-33).
            day_fills = fills_for(extra)
            hist_arms = {}
            for a in ARMS:
                pnl, lots = 0.0, {}
                for r in day_fills.get(a, []):
                    qty, px = int(float(r["qty"])), float(r["px"])
                    if r["side"] == "buy":
                        lots.setdefault(r["sym"], []).append([qty, px])
                    else:
                        q = qty
                        for lot in lots.get(r["sym"], []):
                            take = min(q, lot[0])
                            pnl += (px - lot[1]) * take * 100
                            lot[0] -= take
                            q -= take
                            if q <= 0:
                                break
                hist_arms[a] = {"equity": None, "day": pnl, "positions": [], "error": None}
            hist_snap = {"ok": True, "arms": hist_arms,
                         "total_day": sum(v["day"] for v in hist_arms.values()), "error": None}
            pp = write_daily(extra, f"{stamp} (backfill, FIFO-from-fills)", hist_snap)
            print(f"[obsidian] backfilled {pp.relative_to(REPO)} "
                  f"day={hist_snap['total_day']:+,.2f}")

    home = REPO / "HOME.md"
    home_text = build_home(date, stamp, market_open, snap)
    week = "\n".join(["## This week", ""] + build_week_table())
    home_text = home_text.replace("## Open loops", week + "\n## Open loops", 1)
    home.write_text(home_text, encoding="utf-8")
    print(f"[obsidian] wrote {home.relative_to(REPO)}")

    shadow = REPO / "SHADOW.md"
    shadow.write_text(build_preregs_board(stamp), encoding="utf-8")
    print(f"[obsidian] wrote {shadow.relative_to(REPO)}")

    n_mem = mirror_memory()
    print(f"[obsidian] mirrored {n_mem} memory notes -> memory-mirror/ (gitignored)")

    idx = REPO / "analysis" / "deep-research" / "INDEX.md"
    idx.write_text(build_deep_research_index(stamp), encoding="utf-8")
    print(f"[obsidian] wrote {idx.relative_to(REPO)}")

    mp = REPO / "MAP.md"
    map_text = build_map(stamp)
    health = build_link_health(_visible_md())
    hl = ["## 🩺 Vault link health", "",
          f"- visible notes: **{health['files']}** · broken wikilinks: "
          f"**{len(health['broken'])}** · orphans (no links either way): "
          f"**{len(health['orphans'])}**"]
    # Targets rendered WITHOUT [[ ]] so the checker never parses its own report as links.
    for src, tgt in health["broken"][:10]:
        hl.append(f"  - ⛔ `{src}` → `{tgt}` unresolved")
    if len(health["broken"]) > 10:
        hl.append(f"  - … +{len(health['broken']) - 10} more")
    hl.append("")
    map_text = map_text.replace("## ⏰ The daily loop", "\n".join(hl) + "\n## ⏰ The daily loop", 1)
    mp.write_text(map_text, encoding="utf-8")
    # Count only real node markers, not the legend line that explains the marker.
    missing = sum(1 for ln in map_text.splitlines()
                  if ln.startswith("- ") and "MISSING" in ln)
    # ASCII-only on stdout: the Windows console is cp1252 and a bare emoji here raises
    # UnicodeEncodeError, which would kill the run AFTER the files were already written
    # (looks like a failure, isn't one). Emoji stay in the file, never in the log line.
    print(f"[obsidian] wrote {mp.relative_to(REPO)}"
          + (f"  !! {missing} MISSING path(s)" if missing else "  (all paths verified)"))

    base = REPO / "journal" / "journal.base"
    base.write_text(JOURNAL_BASE, encoding="utf-8")
    print(f"[obsidian] wrote {base.relative_to(REPO)}")

    print(f"[obsidian] book day P&L {money(snap.get('total_day', 0.0))} · broker_ok={snap.get('ok')}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    try:
        sys.exit(main())
    except Exception as exc:  # noqa: BLE001 -- fail open, never break a caller
        print(f"obsidian_vault_sync: non-fatal error: {exc}")
        sys.exit(0)
