"""setup_taxonomy.py -- the ONE canonical setup-name mapping (queue
SETUP-TAXONOMY-UNNORMALIZED-ACROSS-PNL-SURFACES, filed 2026-09-02).

THE PROBLEM: journal/trades.csv's `setup` column is unnormalized -- case-variant
duplicates split one setup into two P&L buckets (VWAP_CONTINUATION n=45 vs
vwap_continuation n=7; VWAP_RECLAIM_FAILED_BREAK n=3 vs vwap_reclaim_failed_break n=9),
an `UNKNOWN` bucket exists alongside genuinely-blank rows, and one pre-rename legacy
name (`BULLISH_RECLAIM`, from before the 2026-05 ribbon-ride rename -- see CHANGELOG.md
2026-05-07 entry) has no counterpart in the current taxonomy. analysis/trades-enriched
.jsonl inherits the SAME raw setup strings via its own context join (setup/scripts/
trades_enriched.py), so any per-setup rollup built independently over either surface
disagrees with the other on bucket boundaries even when the underlying trades are
identical.

THE FIX: one canonical_setup() applied AT READ TIME wherever a per-setup rollup is
built (backtest/scripts/update_setup_performance.py's trades.csv groupby; any future
trades-enriched.jsonl rollup) -- NEVER by rewriting journal/trades.csv (Rule 8: the
journal is never rewritten) or analysis/trades-enriched.jsonl (regenerated by its own
generator, setup/scripts/trades_enriched.py, from frozen upstream writers). This module
touches neither on-disk artifact; it is a pure read-side normalizer.

WRITERS ARE FROZEN (heartbeat_core.py, fleet_executor.py) until at/after the 09-29
clean-window checkpoint (CLAUDE.md "September clean window" doctrine) -- so the raw
`setup` values on disk stay exactly as written; only the READ-TIME label changes."""
from __future__ import annotations

# Pre-rename / legacy raw setup names -> their current canonical counterpart. Keys are
# matched case-insensitively (the lookup upper-cases before matching), so list each
# alias ONCE in its natural case here.
_ALIASES: dict[str, str] = {
    "BULLISH_RECLAIM": "BULLISH_RECLAIM_RIDE_THE_RIBBON",  # pre-ribbon-ride rename,
    # see CHANGELOG.md 2026-05-07 entry ("BULLISH_RECLAIM at 12:30 ET" -- the strategy
    # was later renamed BULLISH_RECLAIM_RIDE_THE_RIBBON; automation/state/fleet/
    # strategies.py's entry_setups tuple carries only the post-rename name today).
}

# Explicit "this row has no real attribution" markers, beyond a blank/whitespace-only
# string (which canonical_setup() also catches). UNKNOWN is a placeholder value some
# historical writer stamped rather than leaving the column blank -- same meaning.
_UNATTRIBUTED_MARKERS = {"UNKNOWN", "NONE", "NULL", "N/A"}

UNATTRIBUTED = "UNATTRIBUTED"


def canonical_setup(name: "str | None") -> str:
    """The ONE canonical mapping: raw setup string (from either journal/trades.csv's
    `setup` column or analysis/trades-enriched.jsonl's `setup` field) -> canonical
    UPPERCASE setup name.

    Rules (idempotent -- canonical_setup(canonical_setup(x)) == canonical_setup(x)):
      1. None / "" / whitespace-only -> UNATTRIBUTED.
      2. Case-insensitive: the result is always upper-cased, so VWAP_CONTINUATION and
         vwap_continuation collapse to one bucket.
      3. An explicit "no real attribution" marker (UNKNOWN and siblings) -> UNATTRIBUTED
         -- same meaning as blank, different historical spelling.
      4. A known legacy/pre-rename alias -> its current canonical name (_ALIASES).
      5. Anything else -> its own upper-cased, stripped value (a genuinely distinct
         setup, including legacy strategy names with no current counterpart -- e.g.
         bollinger_squeeze, vix_regime_dayside, TRENDLINE_BREAK_RETEST -- which stay
         their OWN bucket, just normalized, since they are not aliases of anything
         else in the current taxonomy)."""
    if name is None:
        return UNATTRIBUTED
    stripped = str(name).strip()
    if not stripped:
        return UNATTRIBUTED
    upper = stripped.upper()
    if upper in _UNATTRIBUTED_MARKERS:
        return UNATTRIBUTED
    if upper in _ALIASES:
        return _ALIASES[upper]
    # allow alias keys to be matched case-insensitively even if a future alias is
    # added in mixed case -- normalize the alias table's own keys the same way.
    for raw_alias, target in _ALIASES.items():
        if raw_alias.upper() == upper:
            return target
    return upper


def rollup_by_setup(rows: "list[dict]", *, setup_field: str = "setup",
                    pnl_field: str = "dollar_pnl") -> "dict[str, dict]":
    """Read-side per-setup rollup helper: {canonical_setup: {"n": int, "pnl": float}}.
    Pure, no I/O -- callers own the CSV/JSONL read. `pnl_field` values that are missing
    or non-numeric contribute n but not pnl (never fabricated, matches the C7 disclosed-
    not-guessed convention used across this repo's other read-side aggregators)."""
    out: dict[str, dict] = {}
    for row in rows:
        canon = canonical_setup(row.get(setup_field))
        bucket = out.setdefault(canon, {"n": 0, "pnl": 0.0})
        bucket["n"] += 1
        raw_pnl = row.get(pnl_field)
        if raw_pnl is None or raw_pnl == "":
            continue
        try:
            bucket["pnl"] += float(raw_pnl)
        except (TypeError, ValueError):
            continue
    for bucket in out.values():
        bucket["pnl"] = round(bucket["pnl"], 2)
    return out
