"""EVENT LONG-VEGA re-price — the PIVOT generated by the short-condor death.

The wide-band de-bias killed the SHORT event condor (event exp/tr -$11.38, 0th
percentile of the random-day null: realized moves blow THROUGH the short strikes).
That same fat event-move distribution is the LONG-vega thesis: BUY a strangle /
straddle pre-print, win when the realized 0DTE move > the FULL premium paid.

WHAT THIS DOES (the inverse of _event_iv_crush_reprice.py)
  1. Point the shared OPRA loader at the WIDE cache (ATM +/- $18, $1 grid, C+P).
  2. For each EVENT day and each matched NON-EVENT day, BUY:
       (A) LONG STRANGLE (primary, cap-fitting): buy the ~16-delta call + ~16-delta
           put — the SAME strikes the dead short condor sold (premium proxy:
           pick the OTM strike whose entry mid is closest to TARGET_WING_PREMIUM).
       (B) LONG STRADDLE (reference): buy the ATM call + ATM put.
  3. PAY the ask at entry (entry mid + per-leg slippage), HOLD to the 0DTE expiry,
     SETTLE at TRUE intrinsic vs the day's SPY close (the move either covers the
     premium paid or it does not). Full premium + theta-to-zero on the OTM legs +
     realistic spread/slippage + commission, both legs.
  4. GATE (long side, same bar):
       (a) net of the FULL premium positive (does the move cover what we paid?),
       (b) BEATS the random-DAY null (L172: is the event move SYSTEMATICALLY bigger
           than a random day's, enough to cover the premium?),
       (c) NOT L173-concentrated (drop-worst-2 / drop-best-2 must not flip the sign
           -- one giant move day must not be the whole edge),
       (d) cap-fits (the qty that clears Safe $600 / Bold $824),
       (e) adequate n (~38-46).

  HONEST PRIOR: if the long side ALSO fails the null, event IV is FAIRLY pricing the
  move and the 0DTE premium class is closed BOTH directions -> climb the search space.

Reuses option_pricing_real loader (repointed to wide) + the event-day list +
the spot/entry plumbing byte-for-byte. Pure offline, $0. NO live edit.
"""

from __future__ import annotations

import datetime as dt
import json
import random
import statistics
import sys
from pathlib import Path

_HERE = Path(__file__).resolve()
_BT = _HERE.parents[1]
if str(_BT) not in sys.path:
    sys.path.insert(0, str(_BT))

import lib.option_pricing_real as opr                              # noqa: E402
from lib import cap_admission as ca                               # noqa: E402
from autoresearch._event_iv_crush_precheck import build_event_days, ENTRY_TIME  # noqa: E402
from autoresearch._pivot_premium_selling import (                 # noqa: E402
    _load_spy_master, _spot_and_decision, _option_cache_dates,
)
from autoresearch._event_iv_crush_precheck import WINDOW_START, WINDOW_END  # noqa: E402

WIDE_DIR = _BT / "data" / "options_event_wide"
WIDE_HALF = 18                  # the fetched band: ATM +/- $18
TARGET_WING_PREMIUM = 0.45      # ~16-delta 0DTE leg proxy (mirror the dead short condor)
WING_PREM_LO, WING_PREM_HI = 0.20, 0.90   # acceptable per-leg premium window for the proxy
ENTRY_SLIP = 0.02               # per-leg half-spread paid on the BUY (byte-for-byte default)
COMMISSION = 0.65               # per contract per side; expiry settle = open only (cash-settled)
ENTRY = ENTRY_TIME              # 10:00 ET (same as the short test)

NONEVENT_MATCH_SEED = 4242      # MUST match the short reprice / fetcher matched draw


def _repoint_loader_to_wide():
    opr.CACHE_DIR = WIDE_DIR
    opr._CONTRACT_BAR_CACHE.clear()


def _entry_mid(date: dt.date, strike: int, side: str) -> float | None:
    """Entry-bar open (~mid) for one leg from the WIDE cache at the 10:05 ET fill bar.
    None if the contract has no bar at/after entry (outside priced band / illiquid)."""
    sym = opr.option_symbol(date, strike, side)
    df = opr.load_contract_bars(sym)
    if df is None or df.empty:
        return None
    if df["timestamp_et"].dt.tz is not None:
        df = df.copy()
        df["timestamp_et"] = df["timestamp_et"].dt.tz_localize(None)
    entry_fill_bar = dt.datetime.combine(date, dt.time(10, 5))
    m = df[df["timestamp_et"] >= entry_fill_bar]
    if m.empty:
        return None
    o = float(m.iloc[0]["open"])
    return o if o > 0 else None


def _pick_wing_strike(date: dt.date, atm: int, side: str) -> tuple[int, float] | None:
    """Pick the OTM strike (put below ATM / call above) whose entry premium is CLOSEST
    to TARGET_WING_PREMIUM within [WING_PREM_LO, WING_PREM_HI] — the ~16-delta proxy,
    the SAME strike the dead short condor SOLD (we now BUY it)."""
    best = None
    rng = range(atm - 1, atm - WIDE_HALF - 1, -1) if side == "P" else range(atm + 1, atm + WIDE_HALF + 1)
    for k in rng:
        prem = _entry_mid(date, k, side)
        if prem is None:
            continue
        if not (WING_PREM_LO <= prem <= WING_PREM_HI):
            continue
        dist = abs(prem - TARGET_WING_PREMIUM)
        if best is None or dist < best[2]:
            best = (k, prem, dist)
    return (best[0], best[1]) if best else None


def _intrinsic(strike: int, side: str, spot_close: float) -> float:
    return max(0.0, spot_close - strike) if side == "C" else max(0.0, strike - spot_close)


def _price_long(date: dt.date, legs: list[tuple[int, str]], spot_close: float) -> dict | None:
    """Buy each leg at the entry ask (mid + slip), settle at TRUE intrinsic vs SPY close.
    Returns per-1-lot economics dict, or None if any leg unpriceable at entry."""
    entry_cost = 0.0       # premium PAID per share (debit)
    settle_value = 0.0     # intrinsic collected per share at expiry
    meta_legs = []
    for strike, side in legs:
        mid = _entry_mid(date, strike, side)
        if mid is None:
            return None
        ask = mid + ENTRY_SLIP            # pay the ask on the BUY
        entry_cost += ask
        intr = _intrinsic(strike, side, spot_close)
        settle_value += intr             # cash-settled at expiry, no exit slippage
        meta_legs.append({"k": strike, "side": side, "entry": round(ask, 2),
                          "intrinsic": round(intr, 2)})
    premium_paid = entry_cost * 100.0
    intrinsic_val = settle_value * 100.0
    commission = COMMISSION * len(legs)  # open only (expiry is cash-settled, no close trade)
    pnl = intrinsic_val - premium_paid - commission
    return {
        "premium_paid": round(premium_paid, 2),
        "intrinsic_value": round(intrinsic_val, 2),
        "commission": round(commission, 2),
        "pnl": round(pnl, 2),
        "legs": meta_legs,
    }


def build_strangle(date: dt.date, atm: int) -> tuple[list[tuple[int, str]], dict] | None:
    cp = _pick_wing_strike(date, atm, "C")
    pp = _pick_wing_strike(date, atm, "P")
    if cp is None or pp is None:
        return None
    call_k, prem_c = cp
    put_k, prem_p = pp
    meta = {"call_k": call_k, "put_k": put_k,
            "prem_c": round(prem_c, 2), "prem_p": round(prem_p, 2),
            "pct_otm_c": round((call_k - atm) / atm * 100, 2),
            "pct_otm_p": round((atm - put_k) / atm * 100, 2)}
    return [(call_k, "C"), (put_k, "P")], meta


def build_straddle(date: dt.date, atm: int) -> tuple[list[tuple[int, str]], dict] | None:
    # ATM call+put must both be priceable at entry.
    if _entry_mid(date, atm, "C") is None or _entry_mid(date, atm, "P") is None:
        return None
    return [(atm, "C"), (atm, "P")], {"call_k": atm, "put_k": atm}


def run_days(spy, day_list, builder):
    fills, skips, metas = [], 0, []
    for d in day_list:
        sd = spy[spy["date"] == d]
        if sd.empty:
            skips += 1
            continue
        decision_dt, spot, spot_close = _spot_and_decision(sd, ENTRY)
        if decision_dt is None or not spot or spot <= 0 or not spot_close:
            skips += 1
            continue
        atm = int(round(spot))
        built = builder(d, atm)
        if built is None:
            skips += 1
            continue
        legs, meta = built
        econ = _price_long(d, legs, spot_close)
        if econ is None:
            skips += 1
            continue
        rec = {"date": d.isoformat(), "spot": round(spot, 2),
               "spot_close": round(spot_close, 2),
               "abs_move": round(abs(spot_close - spot), 2)}
        rec.update(meta)
        rec.update(econ)
        metas.append(rec)
        fills.append(rec["pnl"])
    return fills, skips, metas


def summarize(pnls, metas, label):
    if not pnls:
        return {"label": label, "n": 0}
    s = sorted(pnls)
    wins = [p for p in pnls if p > 0]
    drop_worst2 = s[2:] if len(s) > 2 else []
    drop_best2 = s[:-2] if len(s) > 2 else []
    return {
        "label": label, "n": len(pnls),
        "exp_per_trade": round(statistics.mean(pnls), 2),
        "total_pnl": round(sum(pnls), 2),
        "wr": round(len(wins) / len(pnls), 3),
        "worst_trade": round(min(pnls), 2),
        "best_trade": round(max(pnls), 2),
        "drop_worst2_exp": round(statistics.mean(drop_worst2), 2) if drop_worst2 else None,
        "drop_best2_exp": round(statistics.mean(drop_best2), 2) if drop_best2 else None,
        "avg_premium_paid": round(statistics.mean([m["premium_paid"] for m in metas]), 2),
        "avg_abs_move": round(statistics.mean([m["abs_move"] for m in metas]), 2),
    }


def random_day_null(ev_exp, ne_pnls_by_date, n_sample, reps=2000, seeds=(1, 2, 3, 4, 5)):
    """L172 random-DAY null on the SAME long geometry. 5x2000 bootstrap. Returns the
    pooled percentile of ev_exp + p95 + bootstrap P(event-edge delta <= 0)."""
    pool = list(ne_pnls_by_date.values())
    if n_sample == 0 or not pool:
        return None
    clamped = min(n_sample, len(pool))
    all_exps = []
    for sd in seeds:
        rng = random.Random(sd)
        for _ in range(reps):
            pick = rng.sample(pool, clamped)
            all_exps.append(statistics.mean(pick))
    all_exps.sort()
    below = sum(1 for e in all_exps if e < ev_exp)
    pctile = round(below / len(all_exps), 3)
    p95 = all_exps[int(0.95 * len(all_exps))]
    ne_mean = statistics.mean(pool)
    p_delta_le0 = round(sum(1 for e in all_exps if (ev_exp - e) <= 0) / len(all_exps), 4)
    return {
        "reps_total": len(all_exps), "n_sample": n_sample,
        "n_sample_clamped": clamped, "pool_size": len(pool),
        "null_mean": round(ne_mean, 2), "null_p95": round(p95, 2),
        "event_exp": round(ev_exp, 2), "event_pctile_in_null": pctile,
        "beats_null_p95": bool(ev_exp > p95),
        "selection_delta": round(ev_exp - ne_mean, 2), "boot_P_delta_le0": p_delta_le0,
    }


def cap_check(metas):
    """Long debit cap: the FULL premium paid IS the risk. Find the qty that fits the
    Safe $600 / Bold $824 caps at the average premium, and flag the MIN_CONTRACTS floor."""
    if not metas:
        return {}
    avg_prem = statistics.mean([m["premium_paid"] for m in metas])  # $ per 1-lot
    max_prem = max(m["premium_paid"] for m in metas)
    out = {}
    for acct, cap_d, minq in (("safe", 600.0, ca.SAFE_MIN_CONTRACTS),
                              ("bold", 824.0, ca.BOLD_MIN_CONTRACTS)):
        # qty that fits the cap at the AVG premium and at the WORST (max) premium
        qty_avg = int(cap_d // avg_prem) if avg_prem > 0 else 0
        qty_worst = int(cap_d // max_prem) if max_prem > 0 else 0
        # admissible iff the cap-fitting qty >= the MIN_CONTRACTS floor (else hard DENY)
        fits_avg = qty_avg >= minq
        fits_worst = qty_worst >= minq
        out[acct] = {
            "cap_dollars": cap_d, "min_contracts": minq,
            "avg_premium_per_lot": round(avg_prem, 2),
            "max_premium_per_lot": round(max_prem, 2),
            "qty_fits_at_avg": qty_avg, "qty_fits_at_worst": qty_worst,
            "min3_at_avg_cost": round(avg_prem * minq, 2),
            "min3_at_worst_cost": round(max_prem * minq, 2),
            "cap_fits_at_avg": bool(fits_avg),
            "cap_fits_at_worst": bool(fits_worst),
        }
    return out


def run_structure(name, builder, spy, event_days, matched_nonevent, ev):
    print("\n" + "=" * 72)
    print(f"LONG {name}")
    print("=" * 72)
    ev_pnls, ev_skip, ev_meta = run_days(spy, event_days, builder)
    ne_pnls, ne_skip, ne_meta = run_days(spy, matched_nonevent, builder)

    ev_sum = summarize(ev_pnls, ev_meta, "EVENT")
    ne_sum = summarize(ne_pnls, ne_meta, "NON-EVENT")
    print(f"  EVENT    : {json.dumps(ev_sum)}")
    print(f"     skips: {ev_skip}/{len(event_days)}")
    print(f"  NON-EVENT: {json.dumps(ne_sum)}")
    print(f"     skips: {ne_skip}/{len(matched_nonevent)}")

    block = {"event": ev_sum, "event_skips": ev_skip, "event_days_total": len(event_days),
             "nonevent": ne_sum, "nonevent_skips": ne_skip, "event_metas": ev_meta}
    if ev_sum["n"] == 0:
        block["verdict"] = "DEAD_NO_PRICEABLE_GEOMETRY"
        return block

    ne_by_date = {m["date"]: m["pnl"] for m in ne_meta}
    nul = random_day_null(ev_sum["exp_per_trade"], ne_by_date, ev_sum["n"])
    print(f"  RANDOM-DAY NULL (5x2000): {json.dumps(nul)}")
    block["null"] = nul

    cap = cap_check(ev_meta)
    print(f"  CAP/KILL: {json.dumps(cap)}")
    block["cap"] = cap

    # by event class (broad-based?)
    klass = {}
    for m in ev_meta:
        d = dt.date.fromisoformat(m["date"])
        c = ("FOMC" if d in set(ev["fomc"]) else "CPI" if d in set(ev["cpi"])
             else "NFP" if d in set(ev["nfp"]) else "?")
        klass.setdefault(c, []).append(m["pnl"])
    byclass = {c: {"n": len(v), "exp": round(statistics.mean(v), 2)} for c, v in klass.items()}
    print(f"  BY EVENT CLASS: {json.dumps(byclass)}")
    block["by_class"] = byclass

    # GATE
    g_pos = ev_sum["exp_per_trade"] > 0
    g_null = bool(nul and nul["beats_null_p95"])
    # L173: drop-worst-2 AND drop-best-2 must keep the sign of the headline exp.
    sign = 1 if ev_sum["exp_per_trade"] >= 0 else -1
    dw = ev_sum.get("drop_worst2_exp")
    db = ev_sum.get("drop_best2_exp")
    l173_concentrated = bool(
        db is not None and ev_sum["exp_per_trade"] > 0 and db <= 0)  # edge dies w/o top-2
    g_cap = bool(cap.get("safe", {}).get("cap_fits_at_avg"))
    g_n = ev_sum["n"] >= 30
    survives = all([g_pos, g_null, not l173_concentrated, g_cap, g_n])
    gate = {
        "positive_net_of_premium": g_pos, "beats_null": g_null,
        "l173_concentrated": l173_concentrated, "cap_fits_safe_avg": g_cap,
        "adequate_n": g_n, "n": ev_sum["n"], "survives": survives,
    }
    print(f"  GATE: {json.dumps(gate)}")
    block["gate"] = gate
    block["verdict"] = "LEAD_TO_EDGE" if survives else (
        "STILL_LEAD" if (g_pos and ev_sum["n"] < 30) else "DEAD")
    print(f"  VERDICT[{name}]: {block['verdict']}")
    return block


def main():
    _repoint_loader_to_wide()
    ev = build_event_days()
    spy = _load_spy_master()
    spy_dates = set(spy["date"].unique())
    cache_dates = _option_cache_dates()  # narrow-cache dates universe (same as short test)
    usable = sorted(spy_dates & cache_dates)
    usable = [d for d in usable if WINDOW_START <= d <= WINDOW_END]
    event_set = set(ev["all"])
    event_days = [d for d in usable if d in event_set]
    nonevent_pool = [d for d in usable if d not in event_set]
    rng = random.Random(NONEVENT_MATCH_SEED)
    matched_nonevent = sorted(rng.sample(nonevent_pool, min(len(event_days), len(nonevent_pool))))

    print("=" * 72)
    print("EVENT LONG-VEGA RE-PRICE (buy strangle/straddle, wide cache, settle intrinsic)")
    print("=" * 72)
    print(f"  loader CACHE_DIR -> {opr.CACHE_DIR}")
    print(f"  event days: {len(event_days)}  matched non-event: {len(matched_nonevent)}")
    print(f"  entry {ENTRY} ET, hold-to-0DTE-expiry, settle TRUE intrinsic vs SPY close")
    print(f"  strangle wing proxy: per-leg ~${TARGET_WING_PREMIUM} (16d), slip ${ENTRY_SLIP}/leg")

    out = {
        "geometry": {"target_wing_prem": TARGET_WING_PREMIUM, "entry_et": str(ENTRY),
                     "wide_half": WIDE_HALF, "settle": "true_intrinsic_vs_spy_close",
                     "entry_slip": ENTRY_SLIP, "commission": COMMISSION},
        "event_days": len(event_days), "matched_nonevent": len(matched_nonevent),
    }
    out["strangle"] = run_structure("STRANGLE (primary, cap-fitting)", build_strangle,
                                    spy, event_days, matched_nonevent, ev)
    out["straddle"] = run_structure("STRADDLE (reference)", build_straddle,
                                    spy, event_days, matched_nonevent, ev)

    p = _BT / "autoresearch" / "_state" / "event_iv_crush_long.json"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(out, indent=2, default=str))
    print(f"\nwrote {p}")


if __name__ == "__main__":
    main()
