"""Summarise autoresearch results across all modes after a long run.

Reads each mode's `_state/{mode}/state.json` and produces a side-by-side
comparison ranking modes by validate-window performance (the unbiased
measure). Prints a markdown table; optionally writes to a file.

Usage:
    python -m autoresearch.summarize
    python -m autoresearch.summarize --out analysis/autoresearch_results.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from . import config, state as state_mod


def _load_all_modes() -> dict[str, state_mod.State | None]:
    return {mode: state_mod.load_state(mode=mode) for mode in config.MODES}


def _row(label: str, vals: list) -> str:
    return "| " + label + " | " + " | ".join(str(v) for v in vals) + " |"


def build_summary() -> str:
    states = _load_all_modes()
    modes = list(states.keys())
    lines: list[str] = []
    lines.append("# Autoresearch Run Summary\n")
    lines.append("Generated by `python -m autoresearch.summarize`. Validate-window\n"
                 "metrics are the unbiased measure (the train window was used to\n"
                 "make keep/revert decisions).\n")
    lines.append("")
    lines.append("## Window")
    sample = next((s for s in states.values() if s is not None), None)
    if sample is not None:
        lines.append(f"- Train:    {sample.training_window['start']} -> {sample.training_window['end']}")
        lines.append(f"- Validate: {sample.validate_window['start']} -> {sample.validate_window['end']}")
    lines.append("")

    lines.append("## Iteration counts")
    lines.append("| Mode | Iterations | Kept | Reverted | Keep rate |")
    lines.append("|------|------------|------|----------|-----------|")
    for mode in modes:
        s = states[mode]
        if s is None:
            lines.append(f"| {mode} | (no state) | - | - | - |")
            continue
        kr = (100 * s.modifications_kept / s.iteration) if s.iteration else 0
        lines.append(_row(mode, [s.iteration, s.modifications_kept,
                                 s.modifications_reverted, f"{kr:.0f}%"]))
    lines.append("")

    lines.append("## VALIDATE window - final metrics (unbiased)")
    lines.append("| Mode | Trades | WR | P&L | Expectancy | W/L | Sharpe | Max DD |")
    lines.append("|------|--------|----|----|------------|-----|--------|--------|")
    for mode in modes:
        s = states[mode]
        if s is None or not s.validate_baseline_metrics:
            lines.append(f"| {mode} | (no data) |")
            continue
        v = s.validate_baseline_metrics
        wr = f"{v['win_rate']*100:.0f}%"
        wl = f"{v['wl_ratio']:.2f}x" if v.get('wl_ratio') is not None else "n/a"
        lines.append(_row(mode, [
            v["n_trades"], wr, f"${v['total_pnl']:.0f}",
            f"${v['expectancy']:.0f}", wl,
            f"{v['sharpe_daily']:.3f}", f"${v['max_drawdown']:.0f}",
        ]))
    lines.append("")

    lines.append("## TRAIN window - final metrics (overfitting check)")
    lines.append("| Mode | Trades | WR | P&L | Sharpe | Max DD |")
    lines.append("|------|--------|----|----|--------|--------|")
    for mode in modes:
        s = states[mode]
        if s is None or not s.baseline_metrics:
            lines.append(f"| {mode} | (no data) |")
            continue
        m = s.baseline_metrics
        wr = f"{m['win_rate']*100:.0f}%"
        lines.append(_row(mode, [
            m["n_trades"], wr, f"${m['total_pnl']:.0f}",
            f"{m['sharpe_daily']:.3f}", f"${m['max_drawdown']:.0f}",
        ]))
    lines.append("")

    lines.append("## Final parameter sets")
    for mode in modes:
        s = states[mode]
        if s is None:
            continue
        starting = config.MODES.get(mode, {})
        lines.append(f"\n### {mode.upper()}")
        lines.append("| Param | Starting | Final | Changed |")
        lines.append("|-------|----------|-------|---------|")
        for k in sorted(s.current_params.keys()):
            start_v = starting.get(k, "n/a")
            cur_v = s.current_params[k]
            changed = "**YES**" if cur_v != start_v else ""
            lines.append(f"| {k} | {start_v!r} | {cur_v!r} | {changed} |")
    lines.append("")

    # Pick the winner: highest validate sharpe, breaking ties by validate P&L.
    candidates = [
        (mode, states[mode]) for mode in modes
        if states[mode] is not None and states[mode].validate_baseline_metrics
    ]
    if candidates:
        winner = max(
            candidates,
            key=lambda x: (
                x[1].validate_baseline_metrics["sharpe_daily"],
                x[1].validate_baseline_metrics["total_pnl"],
                x[1].validate_baseline_metrics["win_rate"],
            ),
        )
        v = winner[1].validate_baseline_metrics
        lines.append("## Winner (highest validate sharpe -> P&L -> WR)")
        lines.append(f"**{winner[0].upper()}** - validate sharpe {v['sharpe_daily']:.3f}, "
                     f"WR {v['win_rate']*100:.0f}%, P&L ${v['total_pnl']:.0f}")
    return "\n".join(lines)


def main() -> int:
    import sys
    # Reconfigure stdout to UTF-8 so the Windows cp1252 console doesn't choke
    # on any unicode characters that may show up in mode names or notes.
    try:
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    except (AttributeError, ValueError):
        pass
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()
    summary = build_summary()
    print(summary)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(summary, encoding="utf-8")
        print(f"\nWrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
