# Lesson candidate: a producer widening a field to EVERY row silently broke a consumer's presence-based heuristic

**Found:** 2026-07-23, conductor (AFTERHOURS fire), via STAGE 1 FUNCTION-FIRST check (participation-daily.json read RED both accounts today).

**Symptom:** `automation/state/participation-daily.json` reported `verdict: RED` for both Safe and Bold today (2026-07-23), `orders=0` for both, and `participation_daily.py` sent a Discord alert at 16:10:03 ET saying so. This was WRONG: Bold placed and filled a real 0DTE SPY735P at 11:29 ET (documented independently in STATUS.md's EOD entry, -$305). The instrument built specifically to answer "did the engine actually trade today" reported the opposite of the truth on the one day it mattered.

**Root cause:** `backtest/tools/participation_cascade.py#classify_core_row` classified a row as `STALE_TRIGGER` on `action == "SKIP_STALE_TRIGGER" OR row.get("trigger_bar_et")` (bare truthy check). This fallback was written 2026-07-10 when `trigger_bar_et` had exactly ONE writer in `heartbeat_core.py` — the staleness-relabeling branch — so its mere presence WAS a reliable staleness signal at the time. On 2026-07-20, an UNRELATED fix (DECISION-ROW-SPY-STALENESS, a visibility improvement) made `heartbeat_core.py` stamp `trigger_bar_et` on **every** decision row, stale or not. Nobody revisited the 07-10 consumer-side fallback when the 07-20 producer-side change shipped — the two commits were 10 days and unrelated motivations apart, and neither PR touched the other's file. The presence-based heuristic silently flipped from "true only when stale" to "true on ~100% of rows" the moment the producer widened the field's scope, and `classify_core_row` swallowed every real PLACED/FILLED/SKIP_LATE_ENTRY row into `stale_trigger_bar` from that day forward — for 3 days before this fire caught it live.

**Class:** this is the SAME shape as L234 ("a 'real fills' arm-scope filter can go synthetic-by-omission when the live lineup moves on") and L241/L246/L248 (C14: dead/translated-but-unapplied knobs, vary-and-assert) — a consumer's implicit assumption about a producer field's scope/meaning silently invalidated by an independent, well-intentioned producer-side change. Neither side was "wrong" in isolation; the coupling was never tested.

**Fix shipped:** `_trigger_bar_cross_session(row)` — compares `trigger_bar_et`'s calendar day against the row's OWN `ts_et` day (mirrors `heartbeat_core.py#_stale_trigger_bar`'s actual cross-session definition) instead of a bare presence check. `action == "SKIP_STALE_TRIGGER"` (the unconditional, reliable, single-purpose signal) still ORs in as the primary path. 2 new guard tests pin the exact 2026-07-23 exhibit (a same-day `SKIP_LATE_ENTRY` row, a same-day `PLACED` row) plus the pre-existing cross-session tests were updated to include `ts_et` so they still exercise the corrected contract. 51/51 `test_participation_cascade.py` + `test_participation_daily.py` green; curated safety gate (31+5) PASS. Re-ran `participation_daily.py --date 2026-07-23` against the fix: verdict corrected RED→YELLOW, bold now correctly shows `fills=1`, safe's real blockers (`entry_bar_body_pct_min`, `entry_ceiling_15:00`, `block_level_rejection`) are now visible instead of a single opaque `stale_trigger_bar` bucket. A Discord correction was posted (`conductor_correction` source) alongside the naturally-refreshed `participation_daily` line (verdict changed RED→YELLOW so the de-dup didn't suppress it).

**Proposed guard-graduation (for lesson-author):** when a field gets a SECOND writer (or its writer's scope widens) anywhere in the repo, any consumer that keys off that field's bare truthiness (not an explicit sentinel/enum value) is a latent version of this bug. No generic static check exists for "field scope widened, consumer assumed narrow scope" — but the PATTERN (a `# CORRECTED <date>` comment + a same-day-vs-cross-day-style paired test) is now demonstrated twice (L234, this one) and is the right template for a skill-author writeup: "when adding a field to every row of a shared ledger for visibility, grep every consumer for a bare-presence check on that field name before shipping."

**Scope + revert:** `backtest/tools/participation_cascade.py` (1 function extracted + 1 branch corrected + comments) + `backtest/tests/test_participation_cascade.py` (1 test updated, 2 new) + regenerated `automation/state/participation-daily.json` + `automation/state/participation-cascade.json` + appended `analysis/participation-cascade/2026-07-23.md` + 2 Discord lines (natural correction + explicit note). Zero params/heartbeat_core/filters/placement/exit/CLAUDE.md touched — pure observability-instrument bugfix, engine-benefit, ships per OP-22/26. Revert: `git revert <this commit>` (re-running `participation_daily.py --date 2026-07-23` after a revert will re-write the (wrong) RED state file, which is expected/reversible).
